### PR TITLE
Try PkgConf first to find CBLAS

### PR DESCRIPTION
**Pull request by marbre**
Quite similar to PR #988. This fixes issue #761. Any feedback is appreciated.

### CODE REVIEW

**Comment by pavanky** [comment]
We can't have PkgConf as REQUIRED on windows. It needs to be optional and only be enabled on Linux systems.

**Comment by marbre** [comment]
Thanks for the comment. Removed REQUIRED and made PKG_CHECK_MODULES optional like in FindLAPACKE.cmake.

**Comment by marbre** [comment]
@pavanky Removed the MESSAGE here and also in PR #988.

**Comment by pavanky** [comment]
@marbre Sorry to do this again, I think the commits need to go to hotfixes-3.1.1 instead of devel.

**Comment by marbre** [comment]
@pavanky No problem. Done so for the FindLAPACKE.cmake PR too.

**Pull request closed without merging**
