### PR TITLE
Add s64 and u64 to missing functions

### LINKED ISSUE #900: Add 64 bit integer support for relevant functions
List of functions:

- [x] bilateral
- [x] iota
- [x] range
- [x] diff1
- [x] diff2
- [x] minfilt
- [x] medfilt
- [x] maxfilt
- [x] flip
- [x] histogram
- [x] af_join_many
- [x] match_template
- [x] mean_shift
- [x] median
- [x] median_all
- [x] morph
- [x] morph3d
- [x] accum
- [x] set unique
- [x] set intersect
- [x] shift
- [x] sobel
- [x] sort
- [x] tile

### PR DESCRIPTION
**Pull request by shehzan10**
Fixes #900 
* Bilateral, Medfilt, Erode/Dilate MinFilt/MaxFilt, Match Template, Meanshift, Sobel, DOG, RGB2GRAY
* Lookup
* Histogram and HistEq
* Convolve, FFT Convolve
* Sort, Sort index, Sort by key
* Median, Median all
* Set functions

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by pavanky** [comment]
@umar456 Can you look at this ?

**Comment by umar456** [comment]
@pavanky Does it make sense to support intl and uintl data types for all of these functions?

**Comment by pavanky** [comment]
@umar456 I do not know if it is necessary. But if they can be implemented (fairly easily), I do not see any reason to not support them.

**Comment by umar456** [comment]
I don't think we should add these just because they are easy. It will increase the binary size and almost no one will use these functions intentionally. It doesn't make sense to create 64 bit per channel images.

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by shehzan10** [comment]
I'm not sure why but this PR fails to build on windows when launched automatically. When kicked off manually, the build was successful ([build 286](http://ci.arrayfire.org/job/arrayfire-windows-pull/286/)).

This PR is ready to merge now.

**Comment by umar456** [comment]
Accidentally pushed these changes without the --no-ff flag.

Merged:
a479c25 * devel upstream/devel 64bit_picks Add intl/uintl to meanshift
2e36523 * Add intl/uintl to set functions
401f130 * Add intl/uintl to convolve and fftconvolve
5ff4efc * Add intl/uintl to histogram and histeq
c0cb5cd * Add intl/uintl to lookup
d60ae28 * use cl_long and cl_ulong in sort functions
778b13f * Add intl/uintl to sort, sort_index, sort_by_key

**Pull request closed without merging**
