### PR TITLE
Always use freeimage flags instead of hardcoded offsets

### PR DESCRIPTION
**Pull request by pavanky**

### CODE REVIEW

**Comment by pavanky** [comment]
Don't merge this yet, this is causing test failures. Trying to figure out why.

**Comment by pavanky** [comment]
Alright tested that it works on my machine.

**Comment by pavanky** [comment]
build arrayfire linux ci
build arrayfire osx ci

**Comment by shehzan10** [comment]
Verified that the image processing demos are working properly. Merging

**Pull request merged**
