### PR TITLE
BUGFIX: Do not reset JIT tree height after eval

### LINKED ISSUE #1646: BUG in CUDA / OpenCL JIT
Code to reproduce:
```
af::array test1 = af::randn(10, 10);
af::array test2 = af::randn(10);
af::array test3 = af::randn(10);

for (int i = 0; i < 1000; i++) {
    test3 += af::sum(test1, 1);
    test2 += test3;
}
```

This happens when JIT tries to compile a kernel with too many inputs. The force evaluation criteria should be more strict.

First reported here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/arrayfire-users/nqUT8dtlxeo/Ldbi3EfjBAAJ

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #1646

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by pavanky** [comment]
@shehzan10 I updated the PR to have the relevant tests. It is ready to be merged once the tests pass.

**Comment by shehzan10** [comment]
The OpenCL Test for this issue failed ([link](http://ci.arrayfire.org/job/arrayfire-osx/job/pr-build-opencl/25/testReport/junit/projectroot/test/Test_jit_opencl/))

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Pull request merged**
