### PR TITLE
Build time improvements for Scan By Key

### PR DESCRIPTION
**Pull request by shehzan10**
* Fix cl2hpp dependency for scan compilation
* Split scan*.cu files
* Remove dim template from scan_dim

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire linux minimal ci

**Comment by pavanky** [comment]
can you also split files inside `src/backend/cuda/scan_by_key` ?

**Comment by shehzan10** [comment]
I split both cuda/scan.cu and cuda/scan_by_key.cu

**Comment by shehzan10** [comment]
build arrayfire tegrak1 ci

**Comment by shehzan10** [comment]
build arrayfire tegrak1 ci

**Comment by shehzan10** [comment]
build arrayfire tegrak1 ci

**Comment by shehzan10** [comment]
build arrayfire tegrak1 ci

**Comment by pavanky** [comment]
build arrayfire linux ci

**Comment by shehzan10** [comment]
Moved selected commits into #1524

**Pull request closed without merging**
