### PR TITLE
Memory leak fix in SUSAN feature detector

### LINKED ISSUE #1092: Results from out of bounds indexing is different in CUDA
```
int main()
{
    array a = af::iota(dim4(50, 1, 3)).as(s32);
    uint h_idx[7] = {0, 9, 49, 119, 149, 150, 151};
    array idx(7, h_idx);
    af_print(a);
    af_print(a(idx));
    return 0;
}
```

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #1092 - CUDA backend Indexing bug.

### CODE REVIEW

**Comment by 9prady9** [comment]
This is ready for merge. Pending checks from new Linux nodes can be ignored, those builds were cancelled.

**Comment by 9prady9** [comment]
I will send in another fix in this PR, don't merge this yet please.

**Comment by 9prady9** [comment]
Additional fixes are in. Ready for merge once tests pass.

**Comment by shehzan10** [comment]
@9prady9 can you add a test for the failure case so that we know if it ever happens again?

**Comment by 9prady9** [comment]
Added it.

**Comment by 9prady9** [comment]
build arrayfire ci

**Comment by shehzan10** [comment]
build arrayfire ci

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by shehzan10** [comment]
The windows build passed a manual build http://ci.arrayfire.org/job/arrayfire-windows-pull/300/.

**Pull request merged**
