### PR TITLE
[WIP]: Cleanup FreeImage API Calls

### PR DESCRIPTION
**Pull request by 9prady9**
[skip arrayfire ci]

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire linux ci
build arrayfire osx ci

**Comment by 9prady9** [comment]
@shehzan10 What else needs to be done regarding this ?

**Comment by shehzan10** [comment]
I think one of the things that #1356 wanted to have done was to clean up the switch-case for the templates using the document in the link.
Can you check to see if those can be integrated.

**Comment by 9prady9** [comment]
Will reopen this after rebase from devel and further fixes.

**Pull request closed without merging**
