### PR TITLE
Support for complex inputs in math functions

### LINKED ISSUE #769: complex support for mathematical functions
- trigonometric functions
- exponential functions

### PR DESCRIPTION
**Pull request by Godisemo**
- Fixes #769

### CODE REVIEW

**Comment by pavanky** [comment]
build arrayfire linux ci
build arrayfire osx ci

**Comment by pavanky** [comment]
build arrayfire linux ci
build arrayfire osx ci

**Comment by Godisemo** [comment]
build arrayfire linux ci
build arrayfire osx ci

**Comment by pavanky** [comment]
build arrayfire linux ci

**Comment by pavanky** [comment]
@Godisemo :+1: Thanks for doing these! Are you planning on adding more functions ?

**Comment by Godisemo** [comment]
Yes. I'm working an adding most of them, but got into some issues when I tried to use one of the new functions inside another. Take `tan(z) = sin(z)/cos(z)` for example. Trying to figure out what is wrong.

We will also need test added for the new complex functions.

**Comment by pavanky** [comment]
@Godisemo let me know if I can help!

**Comment by Godisemo** [comment]
@pavanky I think I could use some help to write the tests. I looked into the existing tests in `math.cpp` but have no idea on how to extend it to complex functions.

**Comment by pavanky** [comment]
@Godisemo sorry I missed this message. Can you ping me on gitter tomorrow ? I will be available most of the day.

**Comment by Godisemo** [comment]
I will not have time to write the tests for this in at least two weeks. We will have to put this PR on hold until then I guess.

**Comment by pavanky** [comment]
@Godisemo In that case I will write the tests and make any fixes that are necessary. Thanks for the contributions!

**Comment by pavanky** [comment]
Being fixed by #1507

**Pull request closed without merging**
