### PR TITLE
Updated README.md to mention Julia and Nim wrappers.

### LINKED ISSUE #1549: Mention julia wrapper
Would be nice to also mention https://github.com/JuliaComputing/ArrayFire.jl as a wrapper for ArrayFire.

### PR DESCRIPTION
**Pull request by mlloreda**
Fixes #1549

### CODE REVIEW

**Comment by mlloreda** [comment]
skip arrayfire linux ci
skip arrayfire windows ci
skip arrayfire osx ci

**Comment by 9prady9** [comment]
@mlloreda The builds have already started, can you cancel the builds on `ci`?

**Comment by mlloreda** [comment]
@9prady9 done.

**Comment by 9prady9** [comment]
@mlloreda Thank you. Lets merge this other builds.

**Pull request merged**
