### PR TITLE
simplify freeimage cmake code

### PR DESCRIPTION
**Pull request by glehmann**
avoid using cmake's cache where not required
use FindPackageHandleStandardArgs to properly deal with find_package options
merge windows and unix code and use HINTS to find freeimage in the project dir

### CODE REVIEW

**Comment by pavanky** [comment]
@glehmann This pull request errors out if there is no free image installed in the system. We had free image as an optional dependency. Can you make sure the old behavior is preserved ?

**Comment by glehmann** [comment]
I don't have any error here with or without FreeImage.

Have you tested it in a new build tree? The errors may come from the old values in cmake cache.

**Comment by pavanky** [comment]
I just did a clean checkout of your repo and used the cmake-freeimage branch

I get the following error when I do `cmake ..`

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FREEIMAGE_INCLUDE_PATH (ADVANCED)
   used as include directory in directory /tmp/arrayfire
   used as include directory in directory /tmp/arrayfire/src/backend/cpu
   used as include directory in directory /tmp/arrayfire/test
   used as include directory in directory /tmp/arrayfire/test
   used as include directory in directory /tmp/arrayfire/test
   used as include directory in directory /tmp/arrayfire/test
```

**Comment by pavanky** [comment]
Btw, I am using cmake 3.1.3 on a Linux machine.

**Comment by glehmann** [comment]
My bad, I tested the wrong branch… I'll fix that today :-)


2015-03-09 9:26 GMT+01:00 Pavan Yalamanchili <notifications@github.com>:

**Comment by pavanky** [comment]
@glehmann Sorry I did not realize you pushed the changes to this pull request! I am currently building to make sure everything builds. If you make an update, can you please leave a comment next time! It would be easier for us to track that than github notifications.

**Pull request merged**
