### PR TITLE
Bugfixes when getting device pointers and destroying arrays. 

### LINKED ISSUE #1311: Return cl_mem when calling requesting device pointer for OpenCL backend.
Right now it is a (void *) of cl::Buffer *. This should not break the behavior too much anyway because people should be using helper functions from opencl.h anyway.

### LINKED ISSUE #1316: af::arrray.device<>() returns NULL without eval
Not sure if this is intended behavior. But if it is, it should be added to the documentation of `device()`:

```C++
af::setBackend(AF_BACKEND_CPU);

float v[] = {1, 2, 3, 4, 5};
array v_array = array(5, v);

array a_cpu = constant(0, 5,5);

a_cpu += matmulNT(v_array, v_array);
a_cpu.eval(); //Without this eval the device pointer is NULL. 
float *ptr = a_cpu.device<float>();
std::cout << "PTR: " << ptr << std::endl;
```

### LINKED ISSUE #1321: Destructors fail when array was created on different device.
Test: benchmark/blas fails when running on non default device.

### LINKED ISSUE #1324: With OpenCL af_get_data_ptr() seg faults on empty arrays
When using the OpenCL backend calling `af_get_data_ptr()` on empty arrays causes a seg fault:
```c++
#include <arrayfire.h>

int main(){
  // af_set_backend(AF_BACKEND_CPU);
  // af_set_backend(AF_BACKEND_CUDA);
  // The other backends are fine, but OpenCL crashes
  af_set_backend(AF_BACKEND_OPENCL);
  af::array a = af::array(0,f32);
  float data[1] = {0};
  // Should not copy anything as array has size 0
  af_get_data_ptr((void *)data, a.get());
  return 0;
}
```

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #1311 
- Fixes #1316 
- Fixes #1321 
- Fixes #1324

### CODE REVIEW

**Comment by pavanky** [comment]
build arrayfire osx ci

build arrayfire windows ci

**Comment by shehzan10** [comment]
build arrayfire osx ci
build arrayfire windows ci

**Comment by shehzan10** [comment]
build arrayfire osx ci
build arrayfire windows ci

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by shehzan10** [comment]
build arrayfire windows opencl ci

**Comment by shehzan10** [comment]
build arrayfire windows opencl ci

**Pull request merged**
