### PR TITLE
Move template specialization to the OpenCL backend.

### PR DESCRIPTION
**Pull request by bkloppenborg**
Fixes issue #1429

### CODE REVIEW

**Comment by pavanky** [comment]
I really don't like having af::array inside src/backend

**Comment by umar456** [comment]
Its either that or `#ifdefs` in src/api

**Comment by pavanky** [comment]
Or remove AFAPI from template instantiation ?

**Comment by pavanky** [comment]
Maybe you need to make it static as well.

**Comment by umar456** [comment]
Then its a different function. The idea is to have the same interface as the `device<T>()` function which is a member function.

**Comment by shehzan10** [comment]
Wouldn't this be an API breaking change or was it a mistake that the declaration was removed too?

**Comment by umar456** [comment]
The API is the same but the definition shouldn't have been in the header. The definition is already in include/af/array.h

**Comment by shehzan10** [comment]
Might be a bad idea, but cast `cl_mem` as `void*` and document it. Users can cast it on their own. CPU/CUDA can return NULL. This way the standard c++ -> c -> backend track can be taken.

**Comment by umar456** [comment]
That is not a good design. It is confusing, not portable, and error prone. I don't understand why this approach is a problem.

**Comment by pavanky** [comment]
@umar456 It shouldn't matter if it is a different function. It exists only within the header. We are not breaking ABI for the library.

**Comment by umar456** [comment]
The ABI is not being broken. A function is being added not removed.

**Pull request merged**
