### PR TITLE
fp16 support: flat, clamp, select_scalar 

### PR DESCRIPTION
**Pull request by gaika**

### CODE REVIEW

**Comment by umar456** [comment]
Thank you for submitting this!. Can you make a unit test for this. Check out PR #2572 for some examples. Basically use the half_float::half to create an array. and check the results.

**Comment by gaika** [comment]
I'm not a C++ person, sorry. Also why do all unary ops for f16 return f32?

**Comment by umar456** [comment]
I can add the tests in a bit.

Unary ops have not been correctly implemented yet. It is something that needs to be fixed.

**Comment by gaika** [comment]
I really need unary ops, have trouble figuring out what's wrong with them :( Can you give a hint of what is missing?

**Comment by umar456** [comment]
Some of the tests I added depends on #2572. I will update once I have that merged in.

**Comment by umar456** [comment]
Rebased and fixed tests.

**Pull request merged**
