### PR TITLE
Build fixes and missing symbols

### LINKED ISSUE #1040: undefined reference to `af_save_image_memory' when freeimage is absent
So when compiling the newest release (also happens on git master) I get this:

    [ 45%] Linking CXX executable approx1_cpu
    ../src/backend/cpu/libafcpu.so.3.2.0: undefined reference to `af_save_image_memory'

Using gcc 5.2.

make verbose=1 output is:

    [ 45%] Linking CXX executable approx1_cpu
    cd /home/svenstaro/src/arrayfire/build/test && /usr/bin/cmake -E cmake_link_script    CMakeFiles/approx1_cpu.dir/link.txt --verbose=1
    /usr/bin/c++   -O3 -DNDEBUG   CMakeFiles/approx1_cpu.dir/approx1.cpp.o  -o approx1_cpu -rdynamic ../src/backend/cpu/libafcpu.so.3.2.0 -pthread ../third_party/gtest/src/googletest-build/./libgtest.a   ../third_party/gtest/src/googletest-build/./libgtest_main.a -Wl,- rpath,/home/svenstaro/src/arrayfire/build/src/backend/cpu:/home/svenstaro/src/arrayfire/build/third_party/ forge/src/forge-ext-build/src -Wl,-rpath-link,/home/svenstaro/src/arrayfire/build/third_party/forge/src/forge- ext-build/src

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #1040

### CODE REVIEW

**Comment by pavanky** [comment]
I tested this on my machine without freeimage and it compiles.

@shehzan10 Can you restart the windows build ?

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by pavanky** [comment]
@shehzan10 looks like the CI for OSX is broken.

**Comment by shehzan10** [comment]
build arrayfire osx ci

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by shehzan10** [comment]
build arrayfire osx ci

**Comment by pavanky** [comment]
@shehzan10 ready for merge

**Pull request merged**
