### PR TITLE
Bugfixes to diag extract and CUDA FFTs

### LINKED ISSUE #1329: diag extraction additional zeros
The example given in http://arrayfire.org/docs/group__data__func__diag.htm doesn't match the output when running the code:

Documentation example:
```
// Extraction
array a = randu(dim4(4, 3));
// a [4 3 1 1]
// 0.0000     0.5328     0.6793
// 0.1315     0.2190     0.9347
// 0.7556     0.0470     0.3835
// 0.4587     0.6789     0.5194

array b = diag(a);
// b [3 1 1 1]
// 0.0000
// 0.2190
// 0.3835
```

However, when running the code, there's an extra zero in the output:

```
af::array a = af::randu(af::dim4(4, 3));
af::array b = af::diag(a);
af::print("b", b);

b
[4 1 1 1]
    0.5488
    0.8579
    0.6459
    0.0000     <-- 

```

### LINKED ISSUE #1332: Convolve3 on multiple devices fails although it succeeds on each device individually
Calling convolve3 on multiple devices fails with the following code, although the inner loop runs successfully on each device individually. Tested on GeForce GTX TITAN Black, 6144 MB, CUDA Compute 3.5
ArrayFire v3.4.0 (CUDA, 64-bit Linux, build 3dbb7a9)
Platform: CUDA Toolkit 7, Driver: 346.46

try {

		int ndevices = getDeviceCount();
		for (int i = 0; i < ndevices ; i++)
		{
		setDevice(i); // hardcoding this to any available device works
		int n = 25; 
		array x = randu(100,100,100); 
		int t_dim = 50; 
		array all_t = randu(t_dim, t_dim, t_dim, n); 
		for (int j = 0; j < n; j++){
             convolve3(x,all_t(span,span,span,j), AF_CONV_EXPAND);  
		}
		}
	} catch (af::exception& e) {
		fprintf(stderr, "%s\n", e.what());
		throw;
	}

### PR DESCRIPTION
**Pull request by shehzan10**
Fixes #1332 
Fixes #1329

### CODE REVIEW

**Comment by pavanky** [comment]
@shehzan10 did you check if fft in OpenCL backend was alright?

**Comment by pavanky** [comment]
@shehzan10 also shorten the second commit message. Put description in new line

**Comment by shehzan10** [comment]
Ah missed the open. Need to fix.
Will shorten the commit too.

**Comment by pavanky** [comment]
build arrayfire linux ci

**Pull request merged**
