### PR TITLE
YCbCr <-> RGB conversion functions

### LINKED ISSUE #532: YCbCr to RGB and vice versa color space conversion functions

### PR DESCRIPTION
**Pull request by 9prady9**
[skip ci]

### CODE REVIEW

**Comment by 9prady9** [comment]
@pavanky check the API and let me know if the API is fine. This PR is not ready for merge yet though functions are done. I will add tests and documentation while you review the code.

**Comment by 9prady9** [comment]
@pavanky This is ready for merge once tests pass.

**Comment by 9prady9** [comment]
@pavanky The failure on OSX is not related to this feature.

**Comment by pavanky** [comment]
@9prady9 You forgot to add the conversion to `af_colorspace`. Also add the enum for YCBCR in `af_cspace_t`

**Comment by pavanky** [comment]
You can use the default `af_ycc` value for the `af_color_space` conversion.

**Comment by pavanky** [comment]
Disregard my last two comments. I did not look at the last commit.

**Pull request merged**
