### PR TITLE
Fixes ORB for cases where no features exist

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by gpryor** [comment]
Nice - - this is supported on CPU, too?

If so I'll need to try it out on my ARM box. Do you have the standard test imagery posted anywhere?

**Comment by pentschev** [comment]
@gpryor yes, it is supported on all backends, but CPU might not be fully optimized yet. There's no test imagery as of now, as I am still working on further requirements (e.g., Hamming matcher). I hope to have some more interesting examples once we have graphics support.

**Comment by gpryor** [comment]
Fantastic. I'll play with the ORB code on my arm box and let you know how it goes. I'll donate some test imagery, too.

**Comment by pentschev** [comment]
@gpryor that would be awesome. There are actually two test images for unit tests only, but not to show ORB at work.

**Pull request merged**
