### PR TITLE
Workarounds for POCL and Beignet

### PR DESCRIPTION
**Pull request by pavanky**
- Addresses #1575

### CODE REVIEW

**Comment by shehzan10** [comment]
Should we launch OpenCL CI build for this?

**Comment by pavanky** [comment]
@shehzan10 I was waiting to see if I could fix anything else.

 This PR does not solve all the issues on those two platforms yet.

**Comment by pavanky** [comment]
@shehzan10 this can be built too

**Comment by shehzan10** [comment]
build arrayfire linux ci
build arrayfire osx ci
build arrayfire windows ci

**Pull request merged**
