### PR TITLE
Remove std::complex from c++ API. Template constant

### PR DESCRIPTION
**Pull request by umar456**
* Remove std::complex from API
* Templated af::constant function

### CODE REVIEW

**Comment by mateuscfonseca** [comment]
I am not being able to create an array from an std::complex<double>;
Example
std::complex<double> vec[size];
array ar(size, vec);

this is the error
undefined reference to `af::array::array<std::complex<double> >(long long, std::complex<double> const*, af_source)'

**Comment by pavanky** [comment]
@mateuscfonseca you will need to cast the pointer to af::cfloat for this to work.

**Comment by mateuscfonseca** [comment]
I've tried with the two. The code was functioning until today when I update the repo e made a recompile process. 

std::complex<float> vec[size];
array ar(size, vec);

erro: undefined reference to `af::array::array<std::complex<float> >(long long, std::complex<float> const*, af_source)'

std::complex<double> vec[size];
array ar(size, vec);

erro: undefined reference to `af::array::array<std::complex<float> >(long long, std::complex<float> const*, af_source)'

**Comment by pavanky** [comment]
@mateuscfonseca We made a change to remove dependency on `std::complex` when releasing 3.0.

You will need to do the following:

```
array ar(size, (af::cfloat *)vec));
``

This should work.

**Comment by mateuscfonseca** [comment]
@pavanky  thank you very much. English it is not my home languange, so sometimes i dont fully understand things. Now everything makes sense.  Have a very nice day sir (:

**Comment by pavanky** [comment]
No problem. Glad we could help. If you have any questions, you can email us on or [mailing list](https://groups.google.com/forum/#!forum/arrayfire-users) or contact us via our [chat room](https://gitter.im/arrayfire/arrayfire).

**Pull request merged**
