### PR TITLE
Implementation of SVD for all backends

### LINKED ISSUE #709: GCC compiler warnings
Here is a list of compiler warnings I get when compiling ArrayFire from scratch. None of them are particularly troubling:

CMake warnings:

    Manually-specified variables were not used by the project (gtest):

    CMAKE_CXX_FLAGS_LIBSTDCPP
    -- Build files have been written to:: arrayfire/build/third_party/gtest/src/googletest-build

GCC unused variables

    arrayfire/src/backend/cpu/inverse.cpp:64:9: warning: unused variable ‘out’ [-Wunused-variable]

    arrayfire/src/backend/cpu/solve.cpp:85:13: warning: unused variable ‘info’ [-Wunused-variable]

    arrayfire/src/backend/opencl/magma/geqrf3.cpp:81:20: warning: unused variable ‘cpu_trtri’ [-Wunused-variable]

    arrayfire/src/backend/opencl/magma/unmqr.cpp:174:20: warning: variable ‘lddwork’ set but not used [-Wunused-but-set-variable]

    arrayfire/src/backend/opencl/magma/ungqr.cpp:80:32: warning: variable ‘iinfo’ set but not used [-Wunused-but-set-variable]

GCC uninitialized

    arrayfire/src/backend/opencl/kernel/orb.hpp: In function ‘void opencl::kernel::orb(unsigned int*, opencl::Param&, opencl::Param&, opencl::Param&, opencl::Param&, opencl::Param&, opencl::Param&, opencl::Param, float, unsigned int, float, unsigned int, bool) [with T = float; convAccT = float]’:
    arrayfire/src/backend/opencl/kernel/orb.hpp:251:13: warning: ‘d_y_feat.opencl::Param::data’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             bufferFree(d_y_feat.data);
             ^
    arrayfire/src/backend/opencl/kernel/orb.hpp:250:13: warning: ‘d_x_feat.opencl::Param::data’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             bufferFree(d_x_feat.data);

GCC variable formatting (potentially unnecessary debugging?):

    arrayfire/examples/financial/black_scholes_options.cpp:96:69: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘dim_t {aka long long int}’ [-Wformat=]

### LINKED ISSUE #862: SVD for all backends
Do you plan to implement the Singular Value Decomposition based on cuSolver anytime soon?
Thanks!

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #862 
- Fixes #709

### CODE REVIEW

**Comment by pavanky** [comment]
@shehzan10 The OpenCL backend right now requires CBLAS as well. Can you update our jenkins jobs appropriately ?

**Comment by pavanky** [comment]
@klemmster The merge is finally coming into devel :) 

I had to change the API a little bit from the SVD branch.. The order of the outputs is now `svd(U, S, Vt, in)`. 

This was done to reflect the order in which they should be multiplied to reconstruct the original result. I hope this does not break too much on your end.

**Comment by shehzan10** [comment]
OSX requires you to define the following LAPACKE->LAPACK interfaces:
* gesdd
* lamch
* lacpy
* orgbr
* ungbr
* bdsqr

I think that's the list from the errors I see.

**Comment by shehzan10** [comment]
I'm checking to see why linux is failing. We use MKL for PR builds.

**Comment by shehzan10** [comment]
OSX-x64 is expected to fail svd_dense_opencl. I have added the exclusion to the PR builder.

**Pull request merged**
