### PR TITLE
feature: array based indexing operations

### LINKED ISSUE #245: feature: array based indexing operations
Potential API implementations might look as below:
C API
    `af_array_index(af_array *out, const af_array in, const af_array indices, const unsigned dim)`

C++ API
 ```
array array::operator()(const array &arg0);

array array::operator()(const seq &arg0, const array &arg1);
array array::operator()(const array &arg0, const seq &arg1);
array array::operator()(const array &arg0, const array &arg1);

array array::operator()(const array &arg0, const seq &arg1, const seq &arg2);
array array::operator()(const seq &arg0, const array &arg1, const seq &arg2);
array array::operator()(const seq &arg0, const seq &arg1, const array &arg2);
array array::operator()(const array &arg0, const array &arg1, const seq &arg2);
array array::operator()(const seq &arg0, const array &arg1, const array &arg2);
array array::operator()(const array &arg0, const seq &arg1, const array &arg2);
array array::operator()(const array &arg0, const array &arg1, const array &arg2);

array array::operator()(const array &arg0, const seq &arg1, const seq &arg2, const seq &arg3);
array array::operator()(const seq &arg0, const array &arg1, const seq &arg2, const seq &arg3);
array array::operator()(const seq &arg0, const seq &arg1, const array &arg2, const seq &arg3);
array array::operator()(const seq &arg0, const seq &arg1, const seq &arg2, const array &arg3);
array array::operator()(const array &arg0, const array &arg1, const seq &arg2, const seq &arg3);
array array::operator()(const seq &arg0, const array &arg1, const array &arg2, const seq &arg3);
array array::operator()(const seq &arg0, const seq &arg1, const array &arg2, const array &arg3);
array array::operator()(const array &arg0, const seq &arg1, const seq &arg2, const array &arg3);
array array::operator()(const array &arg0, const seq &arg1, const array &arg2, const seq &arg3);
array array::operator()(const seq &arg0, const array &arg1, const seq &arg2, const array &arg3);
array array::operator()(const array &arg0, const array &arg1, const array &arg2, const seq &arg3);
array array::operator()(const array &arg0, const array &arg1, const seq &arg2, const array &arg3);
array array::operator()(const array &arg0, const seq &arg1, const array &arg2, const array &arg3);
array array::operator()(const seq &arg0, const array &arg1, const array &arg2, const array &arg3);
array array::operator()(const array &arg0, const array &arg1, const array &arg2, const array &arg3);
```

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #245

### CODE REVIEW

**Comment by xingchenp** [comment]
@shehzan10 Is array based index available now？

**Comment by 9prady9** [comment]
@xingchenp you would have to add `https://github.com/9prady9/arrayfire` as another git remote url. For example, the way i have my dev folder for arrayfire setup is as follows.
1. set `https://github.com/arrayfire/arrayfire` to `upstream` - main repository
2. set `https://github.com/9prady9/arrayfire` to `origin` - my fork.
3. every time i have some changes/feature additions, i create a new branch from `upstream/devel` and commit my changes in that branch. In this case, it is `array_idx`. To see the changes in that branch, after you do steps (1) & (2) , do `git checkout -b array_idx --track origin/array_idx`

As of now, basic array based indexing is present in that branch. However, operations such as below are not being handled.
```
array a = constant(1, 5, 5);
array A = B(a); // this will work
A(a) = constant(2, 5, 5); // this won't work as of now
```
We are working on the part where we can handle `A(a)` on lhs of assignment as well.

**Comment by xingchenp** [comment]
@9prady9 Thanks.

**Comment by hakttari** [comment]
Dear 9prady9,

The following code, which used to be working in AF2.0, is not working in AF 3.0 with your array_idx function. Please help.

array a = randu(5, 1, f32);
array b = where(a < 0.5);
array c = randu(5, 5, f32);
c(b, 1) = 0;     // error with the following messages

-----------------------------------------------------------------
IntelliSense: more than one instance of overloaded function "af::array::operator()" matches the argument list:
            function "af::array::operator()(const af::array &arg0, const af::seq &arg1) const"
            function "af::array::operator()(const af::array &arg0, const af::array &arg1) const"
            argument types are: (af::array, int)

**Comment by 9prady9** [comment]
@hakttari Please note that this is a work in progress branch, hence i haven't merged it into devel. As for the code you mentioned, `c(b, 1) = 0; ` wouldn't compile because there is no overloaded assignment operator that takes scalar values as arguments as of now.

**Pull request closed without merging**
