### PR TITLE
FEAT: Difference of Gaussians

### PR DESCRIPTION
**Pull request by 9prady9**
* CPU, CUDA & OpenCL backends
* Unit tests for non-batched, batched & invalid inputs
* Documentation

### CODE REVIEW

**Comment by pavanky** [comment]
1. API needs to change. The size of both the gaussian kernels needs to be the same for dog. 
2. Instead of doing `convolve(A, B) - convolve(A, C)`, you can just do `convolve(A, (B - C))`.

**Comment by 9prady9** [comment]
@pavanky Gaussian kernel size doesn't need to be same. Different radius kernels can be used to smooth the the input image.

**Comment by pavanky** [comment]
@9prady9 Yes, but for `dog` force using same size.

**Comment by 9prady9** [comment]
@pavanky I have made the changes.

**Comment by 9prady9** [comment]
[skip ci]

**Comment by 9prady9** [comment]
@pavanky Ready for merge.

**Comment by pavanky** [comment]
Why is resize_cpu failing ??

**Comment by 9prady9** [comment]
Well, i didn't touch that function so i don't think it is related to this change. Must have been failing from earlier i guess.

**Pull request merged**
