### PR TITLE
Compiler warnings fix for image moments functions

### PR DESCRIPTION
**Pull request by syurkevi**

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire linux ci
build arrayfire osx ci

**Comment by shehzan10** [comment]
Looks like you fixed most of it. :+1: 
While you are at it can you fix the gravity sim and other example warnings too?

**Comment by shehzan10** [comment]
build arrayfire linux ci

**Comment by shehzan10** [comment]
@syurkevi Can you fix the gravity sim and warnings from other examples. We'll merge this in following that.

**Comment by pavanky** [comment]
cherry picked here and fixed other warnings as well.

**Pull request closed without merging**
