### PR TITLE
Add FindNVRTC cmake script to locate nvrtc libs correctly

### PR DESCRIPTION
**Pull request by 9prady9**
nvrtc libs are not being found correctly on Ubuntu 16.04. Repurposed
the old FindNVVM.cmake file to locate nvrtc libs.

### CODE REVIEW

**Comment by mlloreda** [comment]
build arrayfire linux ci
build arrayfire osx cuda ci
build arrayfire windows cuda ci

**Comment by mlloreda** [comment]
build arrayfire linux ci
build arrayfire osx cuda ci
build arrayfire windows cuda ci

**Comment by 9prady9** [comment]
build arrayfire linux ci
build arrayfire osx cuda ci
build arrayfire windows cuda ci

**Comment by 9prady9** [comment]
build arrayfire linux ci
build arrayfire osx cuda ci
build arrayfire windows cuda ci

**Pull request merged**
