### PR TITLE
Bug/fix unnecessary include

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by ghisvail** [comment]
Ooops this was not intended. Only the last commit is required. I guess I have to manually rebase onto ```hotfixes-3.0.2```

**Comment by ghisvail** [comment]
sorry ```master``` I meant

**Comment by pavanky** [comment]
@ghisvail I am guessing you branched off devel for the fix ? We need to cherry pick the last commit to hotfixes-3.0.2. I reopened the other PR so we can have the fix in devel as well.

 Just do not do any rebasing for now.

**Comment by ghisvail** [comment]
Too late I just cherry-picked on a different branch and submitted a different PR.

Apologies for the mess. Not much used to the hotfix branch stuff :-(

**Comment by pavanky** [comment]
OK closed everything else and merged it. It's all good.

**Pull request closed without merging**
