### PR TITLE
Complex dot product

### PR DESCRIPTION
**Pull request by FilipeMaia**
Provides dot product for complex arrays.

### CODE REVIEW

**Comment by shehzan10** [comment]
Thanks for this PR.
I believe we should we using dotc (cong(x) . y) instead of dotu.
@pavanky Thoughts?

Also, you missed instantiating the OpenCL templates for complex types.

**Comment by FilipeMaia** [comment]
I think we should have both, but I was planning to have dot call dotu and dotc call dotc.

**Comment by pavanky** [comment]
I agree the default should be dotu 

Let me review it once I'm back in town.

**Comment by pavanky** [comment]
ok to test

**Pull request merged**
