### PR TITLE
FEAT Added 3 and 4 array join functions

### PR DESCRIPTION
**Pull request by shehzan10**
* Changed join kernels to be appending kernels
* Overhead is comparable to previous

### CODE REVIEW

**Comment by pavanky** [comment]
@shehzan10 Can you change `af_join3` and `af_join4` to `af_join_many` ?

The API should be like this:

```
af_join_many(af_array *out, const unsigned n_arrays, const af_array *inputs);
```

You can error out if `n_arrays` is > 4 for now.

**Comment by shehzan10** [comment]
Will there be a limit to how many arrays that can be given to that?

**Comment by pavanky** [comment]
Limit to 4 for now.

**Comment by shehzan10** [comment]
Ok. It will be easy to expand on that because of the way I rewrote the kernels.

**Comment by shehzan10** [comment]
@pavanky added it to allow up to 10 arrays using the C API (only limited by a switch case).
The C++ API is limited to 4 independent arrays.

**Pull request merged**
