### PR TITLE
Fixes for mismatched new/delete operations

### PR DESCRIPTION
**Pull request by 9prady9**

### CODE REVIEW

**Comment by 9prady9** [comment]
build arrayfire linux ci
build arrayfire osx cuda ci
build arrayfire osx opencl ci
build arrayfire windows cuda ci
build arrayfire windows opencl ci

**Comment by 9prady9** [comment]
build arrayfire linux ci
build arrayfire windows ci

**Comment by 9prady9** [comment]
build arrayfire windows ci

**Comment by 9prady9** [comment]
build arrayfire windows ci

**Comment by 9prady9** [comment]
build arrayfire windows ci

**Comment by 9prady9** [comment]
build arrayfire windows ci

**Comment by mlloreda** [comment]
build arrayfire linux ci

**Comment by mlloreda** [comment]
build arrayfire linux ci

**Comment by mlloreda** [comment]
build arrayfire osx ci

**Comment by mlloreda** [comment]
build arrayfire linux ci

**Comment by mlloreda** [comment]
build arrayfire linux ci

**Comment by mlloreda** [comment]
build arrayfire linux ci

**Comment by mlloreda** [comment]
build arrayfire linux ci

**Comment by mlloreda** [comment]
build arrayfire osx ci

**Comment by mlloreda** [comment]
build arrayfire linux ci
build arrayfire osx ci

**Comment by mlloreda** [comment]
build arrayfire osx ci

**Pull request merged**
