### PR TITLE
Tests standalone

### LINKED ISSUE #1108: Make the ArrayFire testsuite a separate project
As for the [examples](https://github.com/arrayfire/arrayfire/blob/devel/examples/CMakeLists.txt), it would be really nice to make the testsuite a separate project, and to support building the tests either with the ArrayFire targets or existing binaries.

The specific use case I have in mind concerns continuous integration inside Linux distributions [1][2], whereby binary packages gets automatically tested on changes to their corresponding dependencies.

[1] https://ci.debian.net
[2] https://fedoraproject.org/wiki/Koschei

### PR DESCRIPTION
**Pull request by shehzan10**
Fixes #1108

Test using
```
cmake arrayfire/test -DArrayFire_DIR=/path/to/af_install/share/ArrayFire/cmake
```

Allows BUILD_NONFREE and USE_RELATIVE_TEST_DIR options as with the previous build action.

Still requires submodules. If not found, will try to init and update them. The expectation is that the source test directory will always be within arrayfire, ie. arrayfire/test.

If the test directory has the submodules, then there is no need for it to be in arrayfire. It can be referred to directly as `cmake /path/to/test -DArrayFire_DIR=/path/to/af_install/share/ArrayFire/cmake`

### CODE REVIEW

**Comment by shehzan10** [comment]
@ghisvail Can you test this out at your end. I've tried to cover most possibilities. Let me know if I missed anything.

**Comment by pavanky** [comment]
@shehzan10 This is not necessary. The test directory should mimic the examples directory. There is no need to introduce the missing cmake modules.

**Comment by shehzan10** [comment]
It is mimicking the examples. The examples directory also has its own CMakeModules directory.

**Comment by pavanky** [comment]
Hmm. Perhaps we need to clean that up as well. Let me review it.

**Comment by shehzan10** [comment]
For the examples, when you ship it with the Installers, the FindOpenCL file is going to be required. Hence the modules directory. Same case with tests.

**Pull request merged**
