### PR TITLE
Unit tests for statistics functions

### LINKED ISSUE #780: Add unit tests for statistics wrapper functions
* [x] mean
* [x] var
* [x] stdev
* [x] cov
* [x] median
* [x] corrcoef

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #780 

Unit tests for the following statistics functions
* median
* corrcoef
* mean
* var
* cov
* stdev

### CODE REVIEW

**Comment by shehzan10** [comment]
I think we are losing a lot of performance here by doing a cast array. In my opinion, the casting should happen at the reduction or at the multiplication of the weights (which is also being casted to output type). https://github.com/arrayfire/arrayfire/blob/devel/src/api/c/stats.h#L46

**Comment by 9prady9** [comment]
I am not entirely sure that is the case, castArray uses JIT i think.

**Comment by shehzan10** [comment]
Just because its JIT does not mean it does not take time. JIT ops when combined with other JIT ops are helpful. Here you are combining one JIT op (castArray) with a reduce_all. Hence the JIT op has to be completed synchronously hence providing no benefit. This essentially turns the castArray into a synchronous memcpy.

**Comment by 9prady9** [comment]
I never said, JIT won't take any time :smile: but agree about what you said regarding castArray turning into synchronous op.

Will try to separate out-type from in-type for common mean function.

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by 9prady9** [comment]
build arrayfire windows ci

**Comment by 9prady9** [comment]
Deferring it through #1034

**Pull request closed without merging**
