### PR TITLE
BUGFIX: Fix Boost compile definitions on Windows

### PR DESCRIPTION
**Pull request by 9prady9**
Without BOOST_CHRONO_HEADER_ONLY compile definition for boost
on Windows, the Boost::boost target will try to link chrono lib
also - which is not needed and thus avoided.

### CODE REVIEW

**Comment by umar456** [comment]
Wouldn't that definition be required for older versions of boost?

**Comment by 9prady9** [comment]
@umar456 Yes, but you are handling that inside `build_boost_compute`. I am fixing the the other case, newer versions.

**Comment by umar456** [comment]
Perhaps remove the flags from boost compute and add it in one location. That way if we decide to add additional flags in the future that target boost we only need to change it in one location.

**Comment by 9prady9** [comment]
@umar456 Please check now.

**Pull request merged**
