### PR TITLE
Fix tests for 32-bit systems

### LINKED ISSUE #1008: Test suite failures on i386 (CPU backend)
The following tests fail for `v3.1.1` on `i386`:
```
	  6 - Test_median_cpu (Failed)
	  9 - Test_reduce_cpu (Failed)
```

The verbose output of CTest gives:

for `test_median_cpu`:
```
 6/85 Test  #6: Test_median_cpu ..................***Failed    0.76 sec
Running main() from gtest_main.cc
[==========] Running 50 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 50 tests from median0
[ RUN      ] median0.float_1D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 1.4901161193847656e-08, which exceeds 1e-8, where
(left + right) / 2 evaluates to 0.50033120810985565,
h_b[off] evaluates to 0.50033122301101685, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.float_1D_even (0 ms)
[ RUN      ] median0.float_2D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 1.4901161193847656e-08, which exceeds 1e-8, where
(left + right) / 2 evaluates to 0.50084446370601654,
h_b[off] evaluates to 0.50084447860717773, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.float_2D_even (39 ms)
[ RUN      ] median0.float_3D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 2.9802322387695312e-08, which exceeds 1e-8, where
(left + right) / 2 evaluates to 0.5086265504360199,
h_b[off] evaluates to 0.50862658023834229, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.float_3D_even (39 ms)
[ RUN      ] median0.float_4D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 1.4901161193847656e-08, which exceeds 1e-8, where
(left + right) / 2 evaluates to 0.49559824168682098,
h_b[off] evaluates to 0.49559825658798218, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.float_4D_even (36 ms)
[ RUN      ] median0.float_flat_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 2.9802322387695312e-08, which exceeds 1e-8, where
(left + right) / 2 evaluates to 0.50583091378211975,
h_b[off] evaluates to 0.50583088397979736, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.float_flat_even (1 ms)
[ RUN      ] median0.float_1D_odd
[       OK ] median0.float_1D_odd (0 ms)
[ RUN      ] median0.float_2D_odd
[       OK ] median0.float_2D_odd (22 ms)
[ RUN      ] median0.float_3D_odd
[       OK ] median0.float_3D_odd (20 ms)
[ RUN      ] median0.float_4D_odd
[       OK ] median0.float_4D_odd (21 ms)
[ RUN      ] median0.float_flat_odd
[       OK ] median0.float_flat_odd (1 ms)
[ RUN      ] median0.int_1D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 56.5, which exceeds 1e-8, where
(left + right) / 2 evaluates to 1065407288.5,
h_b[off] evaluates to 1065407232, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.int_1D_even (0 ms)
[ RUN      ] median0.int_2D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 88, which exceeds 1e-8, where
(left + right) / 2 evaluates to 1125825960,
h_b[off] evaluates to 1125826048, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.int_2D_even (28 ms)
[ RUN      ] median0.int_3D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 32, which exceeds 1e-8, where
(left + right) / 2 evaluates to 1102890784,
h_b[off] evaluates to 1102890752, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.int_3D_even (29 ms)
[ RUN      ] median0.int_4D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 16, which exceeds 1e-8, where
(left + right) / 2 evaluates to 1098607856,
h_b[off] evaluates to 1098607872, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.int_4D_even (29 ms)
[ RUN      ] median0.int_flat_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 24.5, which exceeds 1e-8, where
(left + right) / 2 evaluates to 1035083303.5,
h_b[off] evaluates to 1035083328, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.int_flat_even (0 ms)
[ RUN      ] median0.int_1D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 1.14389e+09
Expected: h_sa[id + off * nx]
Which is: 1143889097
[  FAILED  ] median0.int_1D_odd (0 ms)
[ RUN      ] median0.int_2D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 1.06997e+09
Expected: h_sa[id + off * nx]
Which is: 1069969589
[  FAILED  ] median0.int_2D_odd (22 ms)
[ RUN      ] median0.int_3D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 1.01285e+09
Expected: h_sa[id + off * nx]
Which is: 1012851978
[  FAILED  ] median0.int_3D_odd (23 ms)
[ RUN      ] median0.int_4D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 1.08733e+09
Expected: h_sa[id + off * nx]
Which is: 1087328707
[  FAILED  ] median0.int_4D_odd (22 ms)
[ RUN      ] median0.int_flat_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 1.06553e+09
Expected: h_sa[id + off * nx]
Which is: 1065529583
[  FAILED  ] median0.int_flat_odd (0 ms)
[ RUN      ] median0.uint_1D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 6, which exceeds 1e-8, where
(left + right) / 2 evaluates to 2275588358,
h_b[off] evaluates to 2275588352, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.uint_1D_even (1 ms)
[ RUN      ] median0.uint_2D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 202.5, which exceeds 1e-8, where
(left + right) / 2 evaluates to 2242665674.5,
h_b[off] evaluates to 2242665472, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.uint_2D_even (27 ms)
[ RUN      ] median0.uint_3D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 25.5, which exceeds 1e-8, where
(left + right) / 2 evaluates to 2104942617.5,
h_b[off] evaluates to 2104942592, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.uint_3D_even (26 ms)
[ RUN      ] median0.uint_4D_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 69, which exceeds 1e-8, where
(left + right) / 2 evaluates to 1975044027,
h_b[off] evaluates to 1975044096, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.uint_4D_even (27 ms)
[ RUN      ] median0.uint_flat_even
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:52: Failure
The difference between (left + right) / 2 and h_b[off] is 28.5, which exceeds 1e-8, where
(left + right) / 2 evaluates to 2169638883.5,
h_b[off] evaluates to 2169638912, and
1e-8 evaluates to 1e-08.
[  FAILED  ] median0.uint_flat_even (1 ms)
[ RUN      ] median0.uint_1D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 2.21666e+09
Expected: h_sa[id + off * nx]
Which is: 2216663110
[  FAILED  ] median0.uint_1D_odd (0 ms)
[ RUN      ] median0.uint_2D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 2.16582e+09
Expected: h_sa[id + off * nx]
Which is: 2165821076
[  FAILED  ] median0.uint_2D_odd (20 ms)
[ RUN      ] median0.uint_3D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 2.12973e+09
Expected: h_sa[id + off * nx]
Which is: 2129727047
[  FAILED  ] median0.uint_3D_odd (21 ms)
[ RUN      ] median0.uint_4D_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 2.11073e+09
Expected: h_sa[id + off * nx]
Which is: 2110726127
[  FAILED  ] median0.uint_4D_odd (20 ms)
[ RUN      ] median0.uint_flat_odd
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/median.cpp:47: Failure
Value of: h_b[off]
  Actual: 2.1687e+09
Expected: h_sa[id + off * nx]
Which is: 2168700095
[  FAILED  ] median0.uint_flat_odd (1 ms)
[ RUN      ] median0.uchar_1D_even
[       OK ] median0.uchar_1D_even (0 ms)
[ RUN      ] median0.uchar_2D_even
[       OK ] median0.uchar_2D_even (23 ms)
[ RUN      ] median0.uchar_3D_even
[       OK ] median0.uchar_3D_even (22 ms)
[ RUN      ] median0.uchar_4D_even
[       OK ] median0.uchar_4D_even (23 ms)
[ RUN      ] median0.uchar_flat_even
[       OK ] median0.uchar_flat_even (0 ms)
[ RUN      ] median0.uchar_1D_odd
[       OK ] median0.uchar_1D_odd (0 ms)
[ RUN      ] median0.uchar_2D_odd
[       OK ] median0.uchar_2D_odd (18 ms)
[ RUN      ] median0.uchar_3D_odd
[       OK ] median0.uchar_3D_odd (17 ms)
[ RUN      ] median0.uchar_4D_odd
[       OK ] median0.uchar_4D_odd (17 ms)
[ RUN      ] median0.uchar_flat_odd
[       OK ] median0.uchar_flat_odd (1 ms)
[ RUN      ] median0.double_1D_even
[       OK ] median0.double_1D_even (0 ms)
[ RUN      ] median0.double_2D_even
[       OK ] median0.double_2D_even (29 ms)
[ RUN      ] median0.double_3D_even
[       OK ] median0.double_3D_even (29 ms)
[ RUN      ] median0.double_4D_even
[       OK ] median0.double_4D_even (30 ms)
[ RUN      ] median0.double_flat_even
[       OK ] median0.double_flat_even (0 ms)
[ RUN      ] median0.double_1D_odd
[       OK ] median0.double_1D_odd (1 ms)
[ RUN      ] median0.double_2D_odd
[       OK ] median0.double_2D_odd (22 ms)
[ RUN      ] median0.double_3D_odd
[       OK ] median0.double_3D_odd (21 ms)
[ RUN      ] median0.double_4D_odd
[       OK ] median0.double_4D_odd (22 ms)
[ RUN      ] median0.double_flat_odd
[       OK ] median0.double_flat_odd (0 ms)
[----------] 50 tests from median0 (753 ms total)

[----------] Global test environment tear-down
[==========] 50 tests from 1 test case ran. (753 ms total)
[  PASSED  ] 25 tests.
[  FAILED  ] 25 tests, listed below:
[  FAILED  ] median0.float_1D_even
[  FAILED  ] median0.float_2D_even
[  FAILED  ] median0.float_3D_even
[  FAILED  ] median0.float_4D_even
[  FAILED  ] median0.float_flat_even
[  FAILED  ] median0.int_1D_even
[  FAILED  ] median0.int_2D_even
[  FAILED  ] median0.int_3D_even
[  FAILED  ] median0.int_4D_even
[  FAILED  ] median0.int_flat_even
[  FAILED  ] median0.int_1D_odd
[  FAILED  ] median0.int_2D_odd
[  FAILED  ] median0.int_3D_odd
[  FAILED  ] median0.int_4D_odd
[  FAILED  ] median0.int_flat_odd
[  FAILED  ] median0.uint_1D_even
[  FAILED  ] median0.uint_2D_even
[  FAILED  ] median0.uint_3D_even
[  FAILED  ] median0.uint_4D_even
[  FAILED  ] median0.uint_flat_even
[  FAILED  ] median0.uint_1D_odd
[  FAILED  ] median0.uint_2D_odd
[  FAILED  ] median0.uint_3D_odd
[  FAILED  ] median0.uint_4D_odd
[  FAILED  ] median0.uint_flat_odd

25 FAILED TESTS
```

for `test_reduce_cpu`: 
```
 9/85 Test  #9: Test_reduce_cpu ..................***Failed    0.34 sec
Running main() from gtest_main.cc
[==========] Running 92 tests from 16 test cases.
[----------] Global test environment set-up.
[----------] 8 tests from Reduce/0, where TypeParam = float
[ RUN      ] Reduce/0.Test_sum
[       OK ] Reduce/0.Test_sum (0 ms)
[ RUN      ] Reduce/0.Test_min
[       OK ] Reduce/0.Test_min (1 ms)
[ RUN      ] Reduce/0.Test_max
[       OK ] Reduce/0.Test_max (0 ms)
[ RUN      ] Reduce/0.Test_any_true
[       OK ] Reduce/0.Test_any_true (0 ms)
[ RUN      ] Reduce/0.Test_all_true
[       OK ] Reduce/0.Test_all_true (0 ms)
[ RUN      ] Reduce/0.Test_count
[       OK ] Reduce/0.Test_count (0 ms)
[ RUN      ] Reduce/0.Test_All_Global
[       OK ] Reduce/0.Test_All_Global (28 ms)
[ RUN      ] Reduce/0.Test_Any_Global
[       OK ] Reduce/0.Test_Any_Global (28 ms)
[----------] 8 tests from Reduce/0 (57 ms total)

[----------] 8 tests from Reduce/1, where TypeParam = double
[ RUN      ] Reduce/1.Test_sum
[       OK ] Reduce/1.Test_sum (0 ms)
[ RUN      ] Reduce/1.Test_min
[       OK ] Reduce/1.Test_min (0 ms)
[ RUN      ] Reduce/1.Test_max
[       OK ] Reduce/1.Test_max (0 ms)
[ RUN      ] Reduce/1.Test_any_true
[       OK ] Reduce/1.Test_any_true (0 ms)
[ RUN      ] Reduce/1.Test_all_true
[       OK ] Reduce/1.Test_all_true (0 ms)
[ RUN      ] Reduce/1.Test_count
[       OK ] Reduce/1.Test_count (0 ms)
[ RUN      ] Reduce/1.Test_All_Global
[       OK ] Reduce/1.Test_All_Global (29 ms)
[ RUN      ] Reduce/1.Test_Any_Global
[       OK ] Reduce/1.Test_Any_Global (25 ms)
[----------] 8 tests from Reduce/1 (54 ms total)

[----------] 8 tests from Reduce/2, where TypeParam = af::af_cfloat
[ RUN      ] Reduce/2.Test_sum
[       OK ] Reduce/2.Test_sum (0 ms)
[ RUN      ] Reduce/2.Test_min
[       OK ] Reduce/2.Test_min (0 ms)
[ RUN      ] Reduce/2.Test_max
[       OK ] Reduce/2.Test_max (0 ms)
[ RUN      ] Reduce/2.Test_any_true
[       OK ] Reduce/2.Test_any_true (0 ms)
[ RUN      ] Reduce/2.Test_all_true
[       OK ] Reduce/2.Test_all_true (0 ms)
[ RUN      ] Reduce/2.Test_count
[       OK ] Reduce/2.Test_count (0 ms)
[ RUN      ] Reduce/2.Test_All_Global
[       OK ] Reduce/2.Test_All_Global (16 ms)
[ RUN      ] Reduce/2.Test_Any_Global
[       OK ] Reduce/2.Test_Any_Global (15 ms)
[----------] 8 tests from Reduce/2 (31 ms total)

[----------] 8 tests from Reduce/3, where TypeParam = af::af_cdouble
[ RUN      ] Reduce/3.Test_sum
[       OK ] Reduce/3.Test_sum (0 ms)
[ RUN      ] Reduce/3.Test_min
[       OK ] Reduce/3.Test_min (0 ms)
[ RUN      ] Reduce/3.Test_max
[       OK ] Reduce/3.Test_max (0 ms)
[ RUN      ] Reduce/3.Test_any_true
[       OK ] Reduce/3.Test_any_true (0 ms)
[ RUN      ] Reduce/3.Test_all_true
[       OK ] Reduce/3.Test_all_true (0 ms)
[ RUN      ] Reduce/3.Test_count
[       OK ] Reduce/3.Test_count (0 ms)
[ RUN      ] Reduce/3.Test_All_Global
[       OK ] Reduce/3.Test_All_Global (16 ms)
[ RUN      ] Reduce/3.Test_Any_Global
[       OK ] Reduce/3.Test_Any_Global (16 ms)
[----------] 8 tests from Reduce/3 (32 ms total)

[----------] 8 tests from Reduce/4, where TypeParam = unsigned int
[ RUN      ] Reduce/4.Test_sum
[       OK ] Reduce/4.Test_sum (0 ms)
[ RUN      ] Reduce/4.Test_min
[       OK ] Reduce/4.Test_min (0 ms)
[ RUN      ] Reduce/4.Test_max
[       OK ] Reduce/4.Test_max (0 ms)
[ RUN      ] Reduce/4.Test_any_true
[       OK ] Reduce/4.Test_any_true (0 ms)
[ RUN      ] Reduce/4.Test_all_true
[       OK ] Reduce/4.Test_all_true (0 ms)
[ RUN      ] Reduce/4.Test_count
[       OK ] Reduce/4.Test_count (0 ms)
[ RUN      ] Reduce/4.Test_All_Global
[       OK ] Reduce/4.Test_All_Global (14 ms)
[ RUN      ] Reduce/4.Test_Any_Global
[       OK ] Reduce/4.Test_Any_Global (14 ms)
[----------] 8 tests from Reduce/4 (28 ms total)

[----------] 8 tests from Reduce/5, where TypeParam = int
[ RUN      ] Reduce/5.Test_sum
[       OK ] Reduce/5.Test_sum (0 ms)
[ RUN      ] Reduce/5.Test_min
[       OK ] Reduce/5.Test_min (0 ms)
[ RUN      ] Reduce/5.Test_max
[       OK ] Reduce/5.Test_max (0 ms)
[ RUN      ] Reduce/5.Test_any_true
[       OK ] Reduce/5.Test_any_true (0 ms)
[ RUN      ] Reduce/5.Test_all_true
[       OK ] Reduce/5.Test_all_true (0 ms)
[ RUN      ] Reduce/5.Test_count
[       OK ] Reduce/5.Test_count (0 ms)
[ RUN      ] Reduce/5.Test_All_Global
[       OK ] Reduce/5.Test_All_Global (14 ms)
[ RUN      ] Reduce/5.Test_Any_Global
[       OK ] Reduce/5.Test_Any_Global (14 ms)
[----------] 8 tests from Reduce/5 (28 ms total)

[----------] 8 tests from Reduce/6, where TypeParam = long long
[ RUN      ] Reduce/6.Test_sum
[       OK ] Reduce/6.Test_sum (0 ms)
[ RUN      ] Reduce/6.Test_min
[       OK ] Reduce/6.Test_min (0 ms)
[ RUN      ] Reduce/6.Test_max
[       OK ] Reduce/6.Test_max (0 ms)
[ RUN      ] Reduce/6.Test_any_true
[       OK ] Reduce/6.Test_any_true (0 ms)
[ RUN      ] Reduce/6.Test_all_true
[       OK ] Reduce/6.Test_all_true (0 ms)
[ RUN      ] Reduce/6.Test_count
[       OK ] Reduce/6.Test_count (0 ms)
[ RUN      ] Reduce/6.Test_All_Global
[       OK ] Reduce/6.Test_All_Global (14 ms)
[ RUN      ] Reduce/6.Test_Any_Global
[       OK ] Reduce/6.Test_Any_Global (15 ms)
[----------] 8 tests from Reduce/6 (29 ms total)

[----------] 8 tests from Reduce/7, where TypeParam = unsigned long long
[ RUN      ] Reduce/7.Test_sum
[       OK ] Reduce/7.Test_sum (0 ms)
[ RUN      ] Reduce/7.Test_min
[       OK ] Reduce/7.Test_min (0 ms)
[ RUN      ] Reduce/7.Test_max
[       OK ] Reduce/7.Test_max (0 ms)
[ RUN      ] Reduce/7.Test_any_true
[       OK ] Reduce/7.Test_any_true (0 ms)
[ RUN      ] Reduce/7.Test_all_true
[       OK ] Reduce/7.Test_all_true (0 ms)
[ RUN      ] Reduce/7.Test_count
[       OK ] Reduce/7.Test_count (0 ms)
[ RUN      ] Reduce/7.Test_All_Global
[       OK ] Reduce/7.Test_All_Global (14 ms)
[ RUN      ] Reduce/7.Test_Any_Global
[       OK ] Reduce/7.Test_Any_Global (15 ms)
[----------] 8 tests from Reduce/7 (29 ms total)

[----------] 8 tests from Reduce/8, where TypeParam = unsigned char
[ RUN      ] Reduce/8.Test_sum
[       OK ] Reduce/8.Test_sum (0 ms)
[ RUN      ] Reduce/8.Test_min
[       OK ] Reduce/8.Test_min (0 ms)
[ RUN      ] Reduce/8.Test_max
[       OK ] Reduce/8.Test_max (0 ms)
[ RUN      ] Reduce/8.Test_any_true
[       OK ] Reduce/8.Test_any_true (0 ms)
[ RUN      ] Reduce/8.Test_all_true
[       OK ] Reduce/8.Test_all_true (0 ms)
[ RUN      ] Reduce/8.Test_count
[       OK ] Reduce/8.Test_count (0 ms)
[ RUN      ] Reduce/8.Test_All_Global
[       OK ] Reduce/8.Test_All_Global (13 ms)
[ RUN      ] Reduce/8.Test_Any_Global
[       OK ] Reduce/8.Test_Any_Global (14 ms)
[----------] 8 tests from Reduce/8 (27 ms total)

[----------] 13 tests from Reduce
[ RUN      ] Reduce.Test_Reduce_Big0
[       OK ] Reduce.Test_Reduce_Big0 (5 ms)
[ RUN      ] Reduce.Test_Reduce_Big1
[       OK ] Reduce.Test_Reduce_Big1 (8 ms)
[ RUN      ] Reduce.Test_sum_CPP
[       OK ] Reduce.Test_sum_CPP (0 ms)
[ RUN      ] Reduce.Test_min_CPP
[       OK ] Reduce.Test_min_CPP (0 ms)
[ RUN      ] Reduce.Test_max_CPP
[       OK ] Reduce.Test_max_CPP (0 ms)
[ RUN      ] Reduce.Test_anyTrue_CPP
[       OK ] Reduce.Test_anyTrue_CPP (0 ms)
[ RUN      ] Reduce.Test_allTrue_CPP
[       OK ] Reduce.Test_allTrue_CPP (0 ms)
[ RUN      ] Reduce.Test_count_CPP
[       OK ] Reduce.Test_count_CPP (0 ms)
[ RUN      ] Reduce.Test_Product_Global
/tmp/buildd/arrayfire-3.1.1+dfsg1/test/reduce.cpp:259: Failure
Value of: res
  Actual: 12.6221
Expected: gold
Which is: 12.6222
[  FAILED  ] Reduce.Test_Product_Global (0 ms)
[ RUN      ] Reduce.Test_Sum_Global
[       OK ] Reduce.Test_Sum_Global (1 ms)
[ RUN      ] Reduce.Test_Count_Global
[       OK ] Reduce.Test_Count_Global (0 ms)
[ RUN      ] Reduce.Test_min_Global
[       OK ] Reduce.Test_min_Global (1 ms)
[ RUN      ] Reduce.Test_max_Global
[       OK ] Reduce.Test_max_Global (0 ms)
[----------] 13 tests from Reduce (15 ms total)

[----------] 1 test from MinMax
[ RUN      ] MinMax.NaN
[       OK ] MinMax.NaN (1 ms)
[----------] 1 test from MinMax (1 ms total)

[----------] 1 test from Count
[ RUN      ] Count.NaN
[       OK ] Count.NaN (1 ms)
[----------] 1 test from Count (1 ms total)

[----------] 1 test from Sum
[ RUN      ] Sum.NaN
[       OK ] Sum.NaN (2 ms)
[----------] 1 test from Sum (2 ms total)

[----------] 1 test from Product
[ RUN      ] Product.NaN
[       OK ] Product.NaN (0 ms)
[----------] 1 test from Product (0 ms total)

[----------] 1 test from AnyAll
[ RUN      ] AnyAll.NaN
[       OK ] AnyAll.NaN (1 ms)
[----------] 1 test from AnyAll (1 ms total)

[----------] 2 tests from MaxAll
[ RUN      ] MaxAll.IndexedSmall
[       OK ] MaxAll.IndexedSmall (0 ms)
[ RUN      ] MaxAll.IndexedBig
[       OK ] MaxAll.IndexedBig (2 ms)
[----------] 2 tests from MaxAll (2 ms total)

[----------] Global test environment tear-down
[==========] 92 tests from 16 test cases ran. (337 ms total)
[  PASSED  ] 91 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Reduce.Test_Product_Global

 1 FAILED TEST
```

### PR DESCRIPTION
**Pull request by shehzan10**
[skip ci]

Fixes #1008

### CODE REVIEW

**Comment by shehzan10** [comment]
@pavanky I did a skip ci. If the solution seems ok to you then run the test using the build command.

**Comment by shehzan10** [comment]
build arrayfire ci

**Comment by shehzan10** [comment]
@pavanky @umar456 @9prady9 thoughts on 73b2bb9df17db9df29e31404fa23c7167c3094d2?

**Comment by shehzan10** [comment]
@pavanky updated.

**Comment by 9prady9** [comment]
Think of short name if you can come up with one. otherwise i am good with it.

**Pull request merged**
