### PR TITLE
Fix examples target.

### PR DESCRIPTION
**Pull request by ghisvail**
Installs the content of `examples` under `${AF_INSTALL_EXAMPLE_DIR}`, not `${AF_INSTALL_EXAMPLE_DIR}/examples`. The extra `examples` directory is superfluous.

### CODE REVIEW

**Comment by shehzan10** [comment]
Merged via command line through #1115

**Comment by ghisvail** [comment]
An acknowledgement of the authorship of the commit would have been nice.

**Comment by pavanky** [comment]
@ghisvail I am not sure what you mean, the commit is still under your name and email address. When we say "merged via command line", we do not mean we took the patch and applied manually. It means we did a git pull from github, resolved any conflicts and pushed to the branch manually instead of relying on github.

**Comment by pavanky** [comment]
You could have looked at the linked PR before accusing us of stealing code..

**Comment by ghisvail** [comment]
Honest mistake here. It showed up as shehzan10's commit in the Github frontend. I apologize.

**Comment by pavanky** [comment]
@ghisvail He made another commit earlier today that had a fairly similar commit message and involved additional changes to the same file. This could have been the reason for the confusion.

**Comment by ghisvail** [comment]
Indeed it was. Long day today. Sorry about the mess.

**Pull request closed without merging**
