### PR TITLE
Increase `svd_dense` test thresholds on macOS.

### PR DESCRIPTION
**Pull request by mlloreda**

### CODE REVIEW

**Comment by pavanky** [comment]
Ideally this shouldn't be arbitrary..

**Comment by mlloreda** [comment]
build arrayfire ci

**Comment by mlloreda** [comment]
build arrayfire ci

**Comment by mlloreda** [comment]
build arrayfire osx ci

**Comment by mlloreda** [comment]
build arrayfire osx ci

**Comment by mlloreda** [comment]
build arrayfire osx ci

**Comment by mlloreda** [comment]
build arrayfire osx opencl ci

**Comment by mlloreda** [comment]
build arrayfire osx opencl ci

**Pull request merged**
