### PR TITLE
Update clBLAS release tag

### PR DESCRIPTION
**Pull request by shehzan10**
There are bugs. Do not merge.
Split from #1202 
Ref #947 

[skip ci]

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire ci

**Comment by shehzan10** [comment]
build arrayfire osx ci

**Comment by pavanky** [comment]
@shehzan10 Can you see what's happening on windows?

**Comment by shehzan10** [comment]
build arrayfire windows ci
build arrayfire windows-02 ci

**Pull request merged**
