### PR TITLE
feature: sobel derivatives

### LINKED ISSUE #260: feature: sobel operator
Implement sobel edge detector for all backends.

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #260

### CODE REVIEW

**Comment by pavanky** [comment]
@9prady9 Can you change `af_sobel_dxdy` to something like `af_sobel_operator` ?

**Comment by 9prady9** [comment]
@pavanky good that you actually asked for it. I did a mistake in cpp wrapper arguments. Fixed it now.

**Comment by 9prady9** [comment]
@pavanky this is ready for merge

**Comment by pavanky** [comment]
@9prady9 I need to merge this from command line because of the test data (peter also pushed orb). I will do it after my pull request is merged.

**Pull request merged**
