### PR TITLE
FreeImage Static, Fix for triangle test (under review)

### PR DESCRIPTION
**Pull request by shehzan10**
Default option remains off (ie. uses shared lib).
Known issues:
* The Ubuntu package libfreeimage-dev ships a libfreeimage.a lib. But this lib seems to be incomplete (has undefined symbols). Building a lib from source and then using that made it work successfully
* ~~Currently unable to build Windows with the static lib.~~

### CODE REVIEW

**Comment by shehzan10** [comment]
Also, I just got Windows to build successfully with the static lib. No changes to ArrayFire code required.

**Comment by shehzan10** [comment]
@umar456 @bkloppenborg Please review https://github.com/shehzan10/arrayfire/commit/2cb89c13b2d155c7859cf9982c47f4e94f0159ab

**Comment by bkloppenborg** [comment]
@shehzan10 do any of the projects request acknowledgement if they are used in a project? Do we need to re-post that information?

**Comment by pavanky** [comment]
@bkloppenborg We can either do that in the README or create a separate file if required. For now I think this is sufficient.

**Comment by shehzan10** [comment]
Isn't COPYRIGHT.md acknowledging use? The first line of the intro section states that.

**Pull request merged**
