### PR TITLE
Fixes for Windows for CUDA after C++11 introduction

### PR DESCRIPTION
**Pull request by shehzan10**

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by pavanky** [comment]
@shehzan10 Doesn't windows need specific options to enable C++11 ? If it is automatically enabled, may be there should be checks to see if the compiler version is correct?

**Comment by shehzan10** [comment]
> @shehzan10 Doesn't windows need specific options to enable C++11 ? If it is automatically enabled, may be there should be checks to see if the compiler version is correct?

Nope, that's why CPU/OpenCL never needed it. The existing [C++11 flag in CMakeLists.txt](https://github.com/arrayfire/arrayfire/blob/devel/CMakeLists.txt#L134) is under `if(UNIX)` too.

Visual Studio 2013 has (partial) C++11 support by default. No flags are required.


Ps:
build arrayfire windows ci

**Comment by pavanky** [comment]
Any idea why Windows OpenCL is segfaulting ?

**Comment by shehzan10** [comment]
build arrayfire windows ci

According to @mlloreda, it was a matter of rebooting. Not sure why it happened as I did not touch the OpenCL backend.

**Pull request merged**
