### PR TITLE
[WIP]: Implement approx1 and approx2 along specified dimensions.

### PR DESCRIPTION
**Pull request by pavanky**
Todo:
- [ ] Tests

### CODE REVIEW

**Comment by pavanky** [comment]
@umar456 Do you want https://github.com/arrayfire/arrayfire/pull/1990/commits/3c46ca49f93396da46a4928c308181850b14ed61 in a separate review ? It can probably be ported to 3.5.x

**Comment by umar456** [comment]
Yeah, if you want it backported its probably a good idea.

**Comment by pavanky** [comment]
@umar456 looks like buildbot doesnt like rebases / force pushes?

**Comment by pavanky** [comment]
Benchmark script:
```
int main(int argc, char *argv[])
{
    try {


        // Select a device and display arrayfire info
        int device = argc > 1 ? atoi(argv[1]) : 0;
        af::setDevice(device);
        af::info();

        array Xi = af::seq(0, 1000);
        array Yi = Xi + 3;
        array Xo = 10000 * af::randu(10000);
        af::eval(Xi);
        af::eval(Yi);
        af::eval(Xo);
        af::sync();
        timer::start();
        for (int i = 0; i < 100; i++) {
            array Yo = approx1(Yi, Xo);
        }
        af::sync();
        printf("Time taken: %lf\n", timer::stop());


    } catch (af::exception& e) {

        fprintf(stderr, "%s\n", e.what());
        throw;
    }

    return 0;
}
```
With 3.5.1
- CPU: 0.0068
- CUDA: 0.000613
- OpenCL: 0.0066

With the review
- CPU: 0.0082 (0.83x)
- CUDA: 0.0024 (0.25x)
- OpenCL: 0.0023 (3x, but improvement because of other fixes).

I need to improve the performance.

**Comment by umar456** [comment]
@pavanky It should be able to handle it. Sometimes it fails and I haven't investigated it thoroughly but normally you just have to rebuild and it should work.

**Comment by 9prady9** [comment]
@pavanky is this ready for merge ?

**Comment by 9prady9** [comment]
@pavanky Is this finished ? I see some tests already but there is an unchecked TODO in the PR description.

**Comment by mlloreda** [comment]
Closing this PR. Have made changes to documentation and testing and will submit as a separate PR.

**Pull request closed without merging**
