### PR TITLE
Removed execution permissions of source files

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by pavanky** [comment]
@umar456 Can we add githooks for these kinds of things ? I think this is happening because one of the developers has the default permissions to be 755.

**Comment by umar456** [comment]
@pavanky Yeah, I will look into it

**Comment by pentschev** [comment]
I am not entirely sure about this, but it may be that the files were added to the repo from an NTFS/FAT filesystem.

**Comment by 9prady9** [comment]
@pentschev But addition of new features mostly starts with Linux platform, never on windows.

**Pull request merged**
