### PR TITLE
Fix feature detection functions' 2D to 1D indexing

### PR DESCRIPTION
**Pull request by mark-poscablo**
Some feature detection functions have switched the first and second dimensions when linearizing the 2D indexing of the image data. Issues #2212, #2213, and #2214 all suffer from this problem. I think that this dimension switching is due to the fact that arrayfire is column-major. I also think this was issue hasn't been detected before because the tests use a square image, in which case switching dimensions on the linear array index calculation shouldn't be a problem.

### CODE REVIEW

**Comment by mark-poscablo** [comment]
The last commit (0eeb7ad) should fix #2212 . Though the changes are actually on fast(), orb() uses fast() internally so this change actually fixes both functions.

**Comment by mark-poscablo** [comment]
The last commit (cb06d94) should fix the CPU backend part of #2214 .

**Comment by 9prady9** [comment]
Which program did you use to generate the reference test data ? Also, both fixes seem to switch the first leading dimension with the next leading dimension which doesn't seem to be correct. Also, it is very bad in terms of performance.

**Comment by mark-poscablo** [comment]
@9prady9 Here's the sample code: https://gist.github.com/mark-poscablo/c09078f80476234e0abc27bcc8376e0c. In my perspective, both fixes actually just matches x and y back to the dimensions that they should represent: x is dim1 and and y is dim0. ArrayFire is column major, so isn't this correct? Furthermore, regarding performance - I'm assuming you're talking about the changes on susan here - the index is still incremented by 1 every iteration of the nested for loop, since the inner for loop is iterating through y's, and the index calculation increments by y. This should be cache-friendly data access, no?

**Comment by 9prady9** [comment]
I haven't looked at ORB code, but I looked at fast and susan and they don't swap x & y anywhere through out the algorithm. x is index to the fastest moving dimension and y is index to next fastest dimension, i.e. x is dimension `0`, y is dimension `1` and so on - for any `af::array`. 

`af::loadImage` loads an image such that fastest moving direction of image(scanline) is read as a column in `af::array`, thus fastest moving direction of image is the fastest moving dimension of `af::array`. They don't need to be swapped either while processing features using ArrayFire code or inside other application because x is always pointing to the scanline of image. 

When `af::saveImage` is later used to save an image, it takes care of writing out the image to a file with correct layout.

**Comment by mark-poscablo** [comment]
At this point, due to the due to the potentially overreaching nature of the changes required to fix the root causes of this issue (possibly an API change for `af::loadImage` and other functions affected by it), @umar456 suggested that he take over . Many thanks to @umar456, @9prady9, and @syurkevi for all the help regarding this PR.

**Comment by mark-poscablo** [comment]
By the way, here's the sample program used in this issue: https://github.com/mark-poscablo/arrayfire-featdetect-sample. Simply change the feature detector used inside `get_feats()` to use the desired one.

**Comment by 9prady9** [comment]
@mark-poscablo Is this PR still valid ? If not, lets close it.

**Comment by 9prady9** [comment]
@mark-poscablo Any updates on this PR ?

**Comment by mark-poscablo** [comment]
@9prady9 No, not really. This and #2244 are on hold. Umar said he's going to take over this one since the root issues require an ArrayFire 4.0-wide change.

**Comment by 9prady9** [comment]
Closing for now, please reopen when the necessary changes are done and after a rebase from latest master.

**Comment by mark-poscablo** [comment]
As per my discussion with @9prady9, I'm closing this for now since it's on hold. Let's reopen this when we are ready to make some changes again.

**Pull request closed without merging**
