### PR TITLE
Changed default cuda stream to be non-zero

### LINKED ISSUE #926: Change default stream of CUDA backend
The default stream used to launch all CUDA kernels should not be stream 0. Launching a kernel on stream0 synchronizes all other streams. 

We should create a new stream and use that instead.

Changes to make:
- Launch all kernels with a stream parameter

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #926

### CODE REVIEW

**Comment by shehzan10** [comment]
What about calls to thrust etc? I tried to do a quick search (check for sort), but didn't find any stream changes for that.

**Comment by 9prady9** [comment]
there is something called as `thrust::cuda::par ` , not sure how to use it with other functions, but that's the one i think.

**Comment by shehzan10** [comment]
looks like its similar to a state variable http://stackoverflow.com/questions/24368197/getting-cuda-thrust-to-use-a-cuda-stream-of-your-choice

**Comment by 9prady9** [comment]
It's just another parameter to the functions, thrust functions are overloaded. One of those versions take policy as first argument which is what this thrust::cuda::par thing is.

**Comment by 9prady9** [comment]
This failed on tegra because cuda toolkit version is 6.5 which comes with thrust where `thrust::cuda::par.on` is not available. It is working on linux machine because it was using 7.0 toolkit on that.

**Comment by 9prady9** [comment]
@pavanky this is a block, cuda-6.5 ships with thrust 1.7.2 and this `cuda::par::on` is only available from 1.8.0 version of thrust that comes from cuda-7.0.

**Comment by 9prady9** [comment]
Finally, all :green_apple: @pavanky Please merge it.

**Pull request merged**
