### PR TITLE
Add STGZ, DEB, and RPM installers

### PR DESCRIPTION
**Pull request by bkloppenborg**
Installers tested against Ubuntu 15.04, Debian 8, and Fedora 21.

### CODE REVIEW

**Comment by umar456** [comment]
Can you extract the installation out to another file? The main CMakeLists looks intimidating. You can probably put it in `CMakeModule/Installers.cmake` or something.

**Comment by bkloppenborg** [comment]
@umar456 , this can be done for the packaging step, but the individual `INSTALL` commands need to remain where they are. Would this be acceptable?

**Comment by umar456** [comment]
I was thinking more along the lines of using the [include](http://www.cmake.org/cmake/help/v3.0/command/include.html) command. Creating a packages dir in the root folder seems heavy handed.

**Comment by bkloppenborg** [comment]
Humm... I just realized the OpenCL backend isn't packaging clFFT and similar packages. Is their license permissive enough we can ship the binaries?

**Comment by pavanky** [comment]
@bkloppenborg For reference clBLAS and clFFT are unde Apache license. They can be packaged with ArrayFire if needed.

**Pull request merged**
