### PR TITLE
initial gravity example

### PR DESCRIPTION
**Pull request by syurkevi**
Addresses issue #1144
Needs fixes to collision code. Problems with indexing...
Should simulation speed be based on timestep instead of framerate?

### CODE REVIEW

**Comment by 9prady9** [comment]
@umar456 Yes, convolution with Gaussian is separable, we just need to split the 2d kernel into two separate 1d kernels.

**Comment by pavanky** [comment]
@syurkevi Can you also remove the `#ifdef` for the windows at the end? We realized that we no longer need it and fixed in the hotfixes branch. We fixed for the remaining examples and since this is a new one it is best not to include it at all.

**Comment by unknowazrael** [comment]
@pavanky Can I ask you some other questions? I want to replace the graphics into openGL. But I meet problems. 
1.How can I get the elements from the array? I currently use like this 
image
but I could not free memory (if I add "delete[] host_a", then) 
image
2.What is the right way to do arrayfire+openGL? If I do this every frame  
image
will it spend much time to copy an array on the device to the host?

**Comment by 9prady9** [comment]
@unknowazrael What do you mean by arrayfire+opengl ?

They are following possible ways to do opengl graphics with arrayfire:

- Use arrayfire graphics functionality, which is not currently extensive but good for simple debugging.
- Use arrayfire with your own opengl 
    - via CPU - you don't need anything special but it would be slower than interop option.
    - using opengl interop
        - cpu/cuda backend, you can use current release 3.2.1
        - opencl backend, you would need current devel(beta) build of arrayfire

**Comment by unknowazrael** [comment]
@9prady9 Thanks!  I download v3.2.1 and test success.

**Comment by unknowazrael** [comment]
@9prady9  
Use arrayfire with your own opengl 
  using opengl interop
      cpu/cuda backend, you can use current release 3.2.1

Now I use 3.2.1. May I ask how to using opengl interop? Is there an example?

**Comment by 9prady9** [comment]
@unknowazrael 
- We have [CUDA-Interop example](https://github.com/arrayfire/arrayfire_opengl_interop) code in our github, but i believe this has been written when ArrayFire was v2.*, which is not API compatible with current stable release, v3.*.  However, the set of operations you would need to do for OpenGL interoperation with CUDA backend can be understood from this code.
- As far as CPU backend goes, you just need to use the functions you pointed out earlier: `host<T>` and then copy it into OpenGL buffer for rendering.

**Comment by pavanky** [comment]
@unknowazrael @9prady9 This is getting off topic, can you either create a new issue or discuss this on our gitter chat room?

**Comment by unknowazrael** [comment]
@pavanky Sorry, I have a problem.

How to design collision between particle and particle like this
http://stackoverflow.com/questions/2481479/2d-colliding-n-body-simulation-fast-collision-detection-for-large-number-of-bal

**Comment by pavanky** [comment]
@unknowazrael We can't help you write the code. The example should provide you as a starting point to do what you are looking for.

**Pull request merged**
