### PR TITLE
Updating the cl.hpp version

### PR DESCRIPTION
**Pull request by ghisvail**
This PR allows to build ArrayFire on both `i386` and `amd64` architectures using the latest Khronos OpenCL headers.

### CODE REVIEW

**Comment by ghisvail** [comment]
added another commit which fix a cl::Platform construct inside the `WITH_GRAPHICS` if branch, which I did not test initially but was caught in the Jenkins build logs. Hopefully, this should build fine on osx and linux with `-DBUILD_GRAPHICS=ON` now.

**Comment by 9prady9** [comment]
@ghisvail Thank you, i started the ci builds for linux and osx. Will start windows once they are green.

**Comment by 9prady9** [comment]
@ghisvail Something went wrong in osx build, it is complaining about the following now
```
[ 35%] Building CXX object src/backend/opencl/CMakeFiles/afopencl.dir/platform.cpp.o
/var/lib/jenkins-slave/workspace/arrayfire-osx-pull/src/backend/opencl/platform.cpp:410:45: error: use of undeclared identifier 'CGLGetCurrentContext'
            CGLContextObj cgl_current_ctx = CGLGetCurrentContext();
```
Weird error!

**Comment by ghisvail** [comment]
Seems that a similar problem happened in [Boost.Compute](https://github.com/boostorg/compute/issues/328) and is apparently due to OpenCL - OpenGL interoperability being different on OSX.

Since this is a completely separate issue, I'd suggest to solve it in a different topic branch and merge this PR if all the other platforms are ok.

**Comment by pavanky** [comment]
@ghisvail We can not merge with a branch failing to build

**Comment by ghisvail** [comment]
@pavanky I can't help you further on that. AFAIC this issue is fixed, and I could not care less about OSX specific issues.

**Comment by pavanky** [comment]
@ghisvail I wasn't asking you to fix it. I was simply stating our policy. 

@9prady9 

The old `cl.hpp` file was including GL headers. The new one does not seem to be including any GL headers.

Can you merge this from command line on our osx machine and add the following to `platform.cpp` and check if it is compiling:

```
#if defined(__APPLE__) || defined(__MACOSX)
#include <OpenGL/OpenGL.h>
#include <libkern/OSAtomic.h>
#else
#include <GL/gl.h>
#endif // !__APPLE__
```

**Comment by pavanky** [comment]
@umar456 Well this brings up another question, should we even have `cl.hpp` as a part of our repo ? It looks like cl.hpp is exists everywhere and can be found fairly easily.

**Comment by 9prady9** [comment]
@pavanky I am testing this change now on OSX.

**Comment by shehzan10** [comment]
@pavanky The issue is that (as was previous pointed out) NVIDIA doesn't ship cl.hpp. And the FindOpenCL.cmake does look at the CUDA installation for cl.h (not for cl.hpp). Hence if the CUDA SDK is used for OpenCL headers, it will fail.

There are 2 ways to move forward:
1. Keep the status quo.
2. Remove cl.hpp from the repo and add a cl.hpp requirement to the FindOpenCL.cmake file. This will automatically disqualify all CUDA-based OpenCL header directories. It should not be so much of a problem for our build systems because we generally have an alternate (Intel/AMD) OpenCL SDK installed as well. However, this may become a potential problem for users compiling on windows with only a CUDA SDK. Users may be able to simply download the cl.hpp file and copy it to CUDA/include/CL to make it work.

**Comment by pavanky** [comment]
@umar456 @shehzan10 

I think it would be nice to add option to find `cl.hpp` and if it is not found, automatically download it from Khronos as an external dependency.

**Comment by umar456** [comment]
It looks like the cl.hpp does not have a stable API considering we had to change our source for a minor/patch update. We can do what @pavanky suggested but I am worried how we would handle minor changes to the headers on different systems.

**Comment by 9prady9** [comment]
@pavanky Including GL headers did the trick.

**Comment by pavanky** [comment]
@umar456 Valid point about API breakage. 

@9prady9 Can you merge this PR from command line after changing `platform.cpp` to include GL headers ?

**Comment by ghisvail** [comment]
Please also consider that Khronos no longer ships `cl.hpp` as part of OpenCL 2.0. A new header has been recently added though (`cl2.hpp`). So relying on the availability of a system-installed `cl.hpp` could prove equally as fragile in the future. FYI, Debian unstable now ships the Khronos OpenCL 2.0 headers only.

**Comment by 9prady9** [comment]
Handling this with #961

**Pull request closed without merging**
