### PR TITLE
Convert select, shift to JIT for CUDA and OpenCL

### LINKED ISSUE #1345: Make select a JIT operation
This would require creating a new JIT node called trinary (ternary?) node or generalizing `UnaryNode` + `BinaryNode` to be `FunctionNode`.

### LINKED ISSUE #1732: Implement shift as a JIT compiled function
This will be a special kind of BufferNode that changes the values of indices internally.

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #1345 
- Fixes #1732

### CODE REVIEW

**Comment by 9prady9** [comment]
@pavanky While you are at JIT, can you also look into the following issue as well.
https://github.com/arrayfire/arrayfire/issues/2020

**Comment by pavanky** [comment]
@9prady9 I'll look into it later.

**Comment by pavanky** [comment]
reference benchmark: https://gist.github.com/pavanky/7ee66dde316185d8736038aa614c2b1f Thanks to @mchandra 

Results:

```
######## Kernel compilation ########

Time taken for convolve() kernel compilation = 0.00635 secs
Time taken for shift() kernel compilation    = 0.006131 secs
Time taken for diff1() kernel compilation    = 0.003361 secs

######## All kernel compiled #######


######## Performance results #######


  Input arrays  = vars[10]
  Output arrays = dvars_dx[10]


   ##### convolve() #####

Input dims  = 70 x 70 x 70 x 1
Output dims = 70 x 70 x 70 x 1
Time taken for 1000 diff evaluations = 3.45064 secs


   ##### shift() #####

Input dims  = 70 x 70 x 70 x 1
Output dims = 70 x 70 x 70 x 1
Time taken for 1000 diff evaluations = 2.24695 secs


   ##### diff1() #####

Input dims  = 70 x 70 x 70 x 1
Output dims = 69 x 70 x 70 x 1
Time taken for 1000 diff evaluations = 1.04435 secs


   ##### OpenMP for() loops #####

Time taken for 1000 diff evaluations = 5.02819 secs

-------------------------------------------------------------
######## Kernel compilation ########

Time taken for convolve() kernel compilation = 0.00608 secs
Time taken for shift() kernel compilation    = 0.00187 secs
Time taken for diff1() kernel compilation    = 0.003047 secs

######## All kernel compiled #######


######## Performance results #######


  Input arrays  = vars[10]
  Output arrays = dvars_dx[10]


   ##### convolve() #####

Input dims  = 70 x 70 x 70 x 1
Output dims = 70 x 70 x 70 x 1
Time taken for 1000 diff evaluations = 3.45043 secs


   ##### shift() #####

Input dims  = 70 x 70 x 70 x 1
Output dims = 70 x 70 x 70 x 1
Time taken for 1000 diff evaluations = 1.04684 secs


   ##### diff1() #####

Input dims  = 70 x 70 x 70 x 1
Output dims = 69 x 70 x 70 x 1
Time taken for 1000 diff evaluations = 1.05282 secs


   ##### OpenMP for() loops #####

Time taken for 1000 diff evaluations = 5.01866 secs
```

Tested on:
- CPU: i5 6500
- GPU: GTX 950

Shift is 2.5x faster than what it was before, overall ~5x faster than multi threaded CPU.

**Comment by pavanky** [comment]
@umar456 I know what you are talking about, but I dont think they ever failed for simple ternary ops on scalar values.

**Pull request merged**
