### PR TITLE
Cubic and Bicubic interpolation for approx

### LINKED ISSUE #1289: Cubic / Bicubic interpolation for approx1 and approx2 functions.
Documentation indicates the above options : http://www.arrayfire.com/docs/group__signal__func__approx1.htm

Doesn't look like the code exists: https://github.com/arrayfire/arrayfire/blob/devel/src/backend/opencl/approx.cpp

### PR DESCRIPTION
**Pull request by syurkevi**
Adds cubic/bicubic filtering in the approx1, and approx2 functions for all backends.

- Fixes #1289

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire linux ci
build arrayfire osx ci
build arrayfire windows ci

**Comment by syurkevi** [comment]
So there's some boundary condition problems with approx2. We'll need more comprehensive checks to avoid indexing out of bounds. New commit soon.

**Comment by pavanky** [comment]
Merging this through #1560

**Comment by pavanky** [comment]
@syurkevi I made changes in #1560 to take care of out of bounds conditions.

**Pull request closed without merging**
