### PR TITLE
MIN_BUILD_TIME Option for release build with O0 compilation for speed up

### LINKED ISSUE #1193: Add new build target to reduce compilation times
This option should disable all optimizations. This would be useful during development as well as decrease times to test Pull Requests.

### LINKED ISSUE #1199: Sort tests alphabetically
Tests are not sorted right now. Use CMake sort to sort them alphabetically.

### PR DESCRIPTION
**Pull request by shehzan10**
[skip ci]

Fixes #1193 
Fixes #1199

### CODE REVIEW

**Comment by umar456** [comment]
Fast is misleading. We need to think of a better name

**Comment by shehzan10** [comment]
I'd probably agree. I think `NoOpt`, `FastCompile`, `Unoptimized` are options.

**Comment by pavanky** [comment]
`NoOpt`

**Comment by shehzan10** [comment]
build arrayfire ci

**Comment by shehzan10** [comment]
build arrayfire ci

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Pull request merged**
