### PR TITLE
Fix shfl_down warnings with cuda 9

### PR DESCRIPTION
**Pull request by umar456**

### CODE REVIEW

**Comment by umar456** [comment]
The failures are unrelated to this change.

**Comment by umar456** [comment]
Before
```
ArrayFire v3.6.0 (CUDA, 64-bit Mac OSX, build c78c0d6)
Platform: CUDA Toolkit 9, Driver: CUDA Driver Version: 9010
[0] GeForce GT 750M, 2048 MB, CUDA Compute 3.0
device:  0.02323 seconds to estimate  pi = 3.14140
  host:  0.26709 seconds to estimate  pi = 3.14171
```

After
```
ArrayFire v3.6.0 (CUDA, 64-bit Mac OSX, build c78c0d6)
Platform: CUDA Toolkit 9, Driver: CUDA Driver Version: 9010
[0] GeForce GT 750M, 2048 MB, CUDA Compute 3.0
device:  0.02253 seconds to estimate  pi = 3.14140
  host:  0.26195 seconds to estimate  pi = 3.14171
```

**Comment by biswajitcsecu** [comment]
ArrayFire v3.6.0 (CUDA, 64-bit Mac OSX, build c78c0d6)
Platform: CUDA Toolkit 9,0


libnvrtc.so.9.1: cannot open shared object file: No such file or directory

**Comment by 9prady9** [comment]
@biswajitcsecu Please make sure you had everything in order as per this [Using on OSX](http://arrayfire.org/docs/using_on_osx.htm) tutorial. Also, often so file not found errors are related to missing relevant path(`$AF_PATH/lib` here) in `DYLD_LIBRARY_PATH` (OSX) or `LD_LIBRARY_PATH`(Linux).

**Comment by biswajitcsecu** [comment]
Thank you quick reply. Although I tried before your suggestion and It was solved while I  reconfigured my system with CUDA 9.1.

**Pull request merged**
