### PR TITLE
kernel crashing, due to mismatch with disk cache for updated JIT code.

### PR DESCRIPTION
**Pull request by willyborn**
Disk caching continued loading expired JIT code, resulting in exceptions.  Clearing the disk cached, hided the problem.
For interface changes, an exception was generated.
For all other changes, the old code (initial cached) was loaded and executed.

Description
-----------
JIT code uses the hashing of the function name (based on parameters for JIT) for fast retrieval of the corresponding kernel.  The same hashing was also used to save the code on disk.  When JIT code was updated, the same function name still applies, resulting in an mismatch with a previous saved/cached version.
Static code uses the hashing based on the full code including options.

Now for JIT code, the hashing for disk caching is based on the full code including options (same as static code).  Once the kernel is saved into memory everything remains the same:
  . JIT code remains using the hashing based on function name (no code generation)
  . static code remains using the hashing based on full code + options (hashing is also static)
Result, JIT is now reacting exactly the same as the static code and the correct kernel is always loaded.

* This is a bug fix.
* No new functions, 
* This PR can be back-ported to previous versions. 

Changes to Users
----------------
* No changes to the end-user.  Clearing of the disk cache is no longer needed to eliminate the exception.

Checklist
---------
- [x] Rebased on latest master
- [x] Code compiles
- [x] Tests pass

### CODE REVIEW

**Comment by 9prady9** [comment]
👍🏾 It is awesome that you finally found out the reason for the JIT kernel cache issue. I am just concerned that it increases the startup cost slightly in the case of loading from disk. Did you happen to time by how much the loading time increased with this change ?

@umar456 Is there a way we can actually fix the kernel name generation of JIT ? I was under the impression that JIT kernel names encoded the some form of kernel operations info.

**Comment by willyborn** [comment]
Regarding the JIT kernel names.
It does contain a description of the dynamic calling parameters, incl types etc.
It does not include, the real code or a description of the always present parameters.

As result, fixes in the code, without dynamic interface changes, do result in the same JIT kernel name.
For my opinion, I would keep this, because each time generating the code of those kernels is really time consuming and are static inside one run.  (not between runs/disk caches, since code could have changed).

**Comment by umar456** [comment]
@willyborn I couldn't see the times in the log you posted. I assume its pretty small based on your comments. I can't imagine this hashing would increase the times significantly. I am curious if we can't achieve the same thing by including the AF_REVISION when storing the names. This will allow us to refresh the cache for each commit and avoid issues like this. Can you think of a reason why this would fail?

**Comment by willyborn** [comment]
@umar
I first included the AF_REVISION, as proposed.
l still had to clear the cache for each test run, because this version
number is constant during development recompiles.
I assume the version nr changes after a commit in GitHub, which is not the
case during development.  On my system they never changed.

With the static kernels, I did not have this problem so I searched further
to understand why, with this PR as result.

Regarding the timings: the 1st run gives a theoretical time almost equal to
the static kernel (any run), where the combining of the hashes is always
performed.
I did not give times, because as soon as you put it inside a loop, the
extra steps are no longer executed.  The measured times, before or after
the change, are as result equal.  (I believe we are talking here over
microseconds, if not picoseconds).

PS: Only the combining is performed because the hashing on the code text is
already performed before the call, also before the change.  These hashes
are stored in common::Source struct and are present in the parameters of
the getKernel call.  (also for JIT)

**Pull request merged**
