### PR TITLE
Bug fixes for Sparse Convert on AMD and Intel

### PR DESCRIPTION
**Pull request by shehzan10**
* Fixes out of bounds memory access on AMD/Intel

[skip arrayfire ci]

### CODE REVIEW

**Comment by shehzan10** [comment]
build arrayfire linux ci
build arrayfire osx opencl ci
build arrayfire windows opencl ci

**Comment by pavanky** [comment]
@shehzan10 while you are at it, can you change the kernel caching to match what I did instead of the old method ?

We should move on to using the new method eventually. It'll be nice to have consistency in a single file when we start the cleanup at a later point.

**Comment by shehzan10** [comment]
I actually had the new method in but I thought it was part of the problem and reverted to the old method.
I think it's better to convert all the kernels into the new method at once, maybe for v3.5.0. Maybe we should create an issue for this.

I'll change the kernels in the sparse file to the new format.

**Comment by pavanky** [comment]
> I'll change the kernels in the sparse file to the new format.

Yeah that is all I was asking for now :)

**Comment by shehzan10** [comment]
@pavanky it had been done. give it a review.

**Pull request merged**
