### PR TITLE
Cleaning up interpolation methods.

### LINKED ISSUE #289: AF_INTERP_CUBIC not implemented in resize()
The af::interpType enumeration implies that the following interpolation methods are supported:

```
AF_INTERP_LINEAR
AF_INTERP_CUBIC
AF_INTERP_NEAREST
AF_INTERP_BILINEAR
```

however not all of these interpolation methods are supported in resize as it will generate the following runtime error:

    Expected: (method == AF_INTERP_BILINEAR || method == AF_INTERP_NEAREST)

It seems these additional interpolation methods still need to be added to ArrayFire 2.1.

### LINKED ISSUE #1562: Add new interpolation methods
A good list is available [here](http://paulbourke.net/miscellaneous/interpolation/)

- [x] Cosine
- [x] Cubic
- [x] Spline (Fixed by #1289)

Support all AF_INTERP enums for the following functions:

- [x] resize (done by falling back to scale for new methods)
- [x] transform (scale, rotate, skew, translate etc)
- [x] approx2

### PR DESCRIPTION
**Pull request by pavanky**
- Adding new interpolation methods
- Cleaning up interpolation functions so they can be reused by multiple functions
- Added new interpolation methods

- Fixes #1562 
- Fixes #289

### CODE REVIEW

**Comment by pavanky** [comment]
build arrayfire linux ci
build arrayfire osx ci
build arrayfire windows ci

**Comment by pavanky** [comment]
build windows arrayfire ci

**Comment by shehzan10** [comment]
build arrayfire windows ci

**Comment by shehzan10** [comment]
Looks like M_PI is missing for CPU also. I tested it manually with
```
diff --git a/src/backend/cpu/kernel/interp.hpp b/src/backend/cpu/kernel/interp.hpp
index ed8d6ae..1cc7402 100644
--- a/src/backend/cpu/kernel/interp.hpp
+++ b/src/backend/cpu/kernel/interp.hpp
@@ -16,6 +16,7 @@ namespace cpu
 namespace kernel
 {

+static const float M_PI = 3.1415926535897932384626433832795028841971693993751058209749445923078164;

 template<typename InT, typename LocT>
 InT linearInterpFunc(InT val[2], LocT ratio)

```

**Comment by pavanky** [comment]
@shehzan10 I'll fix it in future commits

**Comment by pavanky** [comment]
build arrayfire windows ci

**Comment by pavanky** [comment]
build arrayfire windows ci

**Pull request merged**
