### PR TITLE
fix the missing external projects byproducts

### PR DESCRIPTION
**Pull request by glehmann**
that were removed in 46111d50cd5daf43b9fc30ba7f6335d08aebc95e

### CODE REVIEW

**Comment by pavanky** [comment]
@glehmann This was causing build failures on Linux.

**Comment by glehmann** [comment]
Sorry about that. Coule you give me thé error message ans cmake version?
Le 31 mars 2015 16:14, "Pavan Yalamanchili" <notifications@github.com> a
écrit :

**Comment by shehzan10** [comment]
Here is the relevant section of the output. Happens to both clBLAS and clFFT.
```
[ 19%] Performing download step (git clone) for 'clFFT-external'
Cloning into 'clFFT-external'...
Note: checking out '1597f0f35a644789c7ad77efe79014236cca2fab'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 1597f0f... Merge pull request #2 from glehmann/arrayfire-static_build_fix
[ 19%] [ 20%] No patch step for 'clFFT-external'
No update step for 'clFFT-external'
[ 20%] Performing configure step for 'clFFT-external'
CMake Error: The source directory "/home/shehzan/area51/arrayfire/build/third_party/clFFT/lib/import/libclFFT.a" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [third_party/clFFT/src/clFFT-external-stamp/clFFT-external-configure] Error 1
make[1]: *** [src/backend/opencl/CMakeFiles/clFFT-external.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by glehmann** [comment]
ok, I see that the condition to set the `byproducts` var is wrong. I'll fix it.

**Comment by pavanky** [comment]
@shehzan10 Can you verify and merge this ?

**Pull request merged**
