### PR TITLE
Documentation for Image Processing Functions

### PR DESCRIPTION
**Pull request by 9prady9**
Documentation for the following functions
* regions
* gaussianKernel
* sobel
* matchTemplate
* medfilt
* meanshift
* bilateral
* erode
* erode3d
* dilate
* dilate3d

### CODE REVIEW

**Comment by safi-huss** [comment]
Hi,
I am trying to use the meanshift function but it is giving me a blank image for some reason. I am finding the documentation a bit inadequate in this regard. Please advise.

Thanks,
-Safi

**Comment by pavanky** [comment]
@safi-huss Can you show some sample code that you are using ? How are you displaying the image?

**Comment by safi-huss** [comment]
sample code is fairly simple,
    array input_image = loadImage("/home/safi/Pictures/cont2.jpg", true);
    array output_image = meanShift(input_image, 32, 32, 5, true);
    saveImage("output.PNG", output_image);

The images are:
output
output

input:
cont2

**Comment by safi-huss** [comment]
On a side node, I get some warning:
`warning, curbe size exceed limitation`
What are the details related to this warning?

**Comment by 9prady9** [comment]
@safi-huss I can't say i exactly reproduced the issue at my end, but i am getting an output image with lot of artifacts in it when i ran the code you gave me (i used the image you provided with exact same parameters). I used opencl backend as cpu backend is taking too long to compute (hence displaying black image for quite some time). Which backend did you use?

**Comment by safi-huss** [comment]
I ve tried both, OpenCL and CPU. both give the same result. BTW I am
running on Ubuntu with the Beignet driver on a Bay-Trail-T processor.

On Wed, Aug 5, 2015 at 6:12 PM, Pradeep Garigipati <notifications@github.com

**Comment by 9prady9** [comment]
@safi-huss Ah, with Beignet, i haven't tried on that one. I don't think we have had 100% successful unit tests pass on Beignet driver.

On the other hand, what ever artifacts i found in my earlier trials, i have put in a fix for it in the devel branch. Just wanted to let you know about that.

If you can, can you please try latest changes in devel on your machine and any other machine with proprietary drivers. This will narrow down the issue to Beignet at the least (which is what the case i think it is).

**Comment by safi-huss** [comment]
Sorry for the delay, How do I switch drivers/devices?

On Fri, Aug 7, 2015 at 6:25 PM, Pradeep Garigipati <notifications@github.com

**Comment by pavanky** [comment]
@safi-huss If you are working on intel GPUs + linux beignet is the only solution. We are trying to figure out why some of our algorithms are failing on this combination.

**Comment by safi-huss** [comment]
I have been able to install old opencl drivers in code builder sdk that
intel provided for some older versions of Ubuntu. Give me a bit to get you
a screen grab

**Pull request merged**
