### PR TITLE
fix freeimage bitmap resource leaks

### PR DESCRIPTION
**Pull request by vakopian**
Currently, in `af_load_image()`, `af_load_image_memory()`, `af_save_image()` and `af_save_image_memory()` functions, if an error happens after the FreeImage bitmap is loaded, these functions are exited (e.g. by throwing an exception) without unloading the bitmap. This results in resource leaks.
The proposed patch fixes this using the RAII wrapper class called `FI_BitmapResource`. The same could be done using the C++11's `unique_ptr`, but I'm not sure if ArrayFire has made the move to the new standard yet.

### CODE REVIEW

**Comment by pavanky** [comment]
Why not use `unique_ptr` and `FreeImage_Unload` as the deleter ?

**Comment by vakopian** [comment]
Right, that would be the preferred way to do it - does ArrayFire already require C++11 compliant compiler ? If yes I'll make another pull request using unique_ptr

**Comment by pavanky** [comment]
Good point. It is required for CPU and OpenCL backends. However the CUDA backend does not require it because older versions of CUDA did not support it.

I am going to accept it and change it to use unique pointers later if it is compliant.

**Comment by pavanky** [comment]
build arrayfire ci

**Comment by pavanky** [comment]
@vakopian These are problems with our build system. We are looking into it.

**Comment by 9prady9** [comment]
build arrayfire ci

**Comment by 9prady9** [comment]
@pavanky I just noticed this, this PR is a bug fix, hence shouldn't it go into hot-fixes for 3.1.1 ?

**Comment by pavanky** [comment]
This isn't critical. It can stay in devel.

**Comment by 9prady9** [comment]
Ok, merging then.

**Pull request merged**
