### PR TITLE
fix for surface rendering function

### LINKED ISSUE #1603: bug in Window::surface function - incorrect surface rendering.
This has been initially been reported via [google group forum post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/arrayfire-users/SMfSfcXVeCM/Qo3R4oc1CAAJ).

Code to reproduce the bug is given below.

```cpp
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;

int main(int argc, char *argv[])
{
    try {
        af::info();

        Window w;

        array A = randu(10, 10);

        w.setAxesLimits(0.0f, 10.0f, 0.0f, 10.0f, 0.0f, 1.0f);

        while(!w.close()) {
            w.surface(A);
        }

    } catch (af::exception& e) {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }

    return 0;
}
```

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #1603

### CODE REVIEW

**Comment by 9prady9** [comment]
@shehzan10 Apparently, regular `modDim` backend function is also doing evaluate before it is modifying the meta data of Array. 

The problem lies in dims being modified before data is evaluated. Since each JIT node is storing the original dims, when eval is called after moddims is done, the node is still using original dims to compute the array values.

@pavanky Does changing `m_dims` member variable in buffer JIT node whenever moddims is called have any side effects ?

**Comment by pavanky** [comment]
@shehzan10 didn't we fix this ?

**Comment by pavanky** [comment]
Ok, it looks like me and shehzan found the exact same bug for when inputs are **NOT** vectors and fixed that. We forgot to fix cases where input is a vector. It is a simple enough fix.

@9prady9 can you look at the following commit and send in a proper patch.
18a4e5547c729ae9bbb45926a4d9d39fea166b38

**Comment by 9prady9** [comment]
@pavanky The fix is using function version of `modDims` instead of `Array::modDims` ?

**Comment by pavanky** [comment]
@9prady9 yes, the function version of modDims is updating the metadata properly. So it is easier to just call that than re-implement changing the metadata in surface.

**Comment by 9prady9** [comment]
@shehzan10 This is ready for merge.

**Comment by pavanky** [comment]
@9prady9 can you look to see if any other functions in `src/api/c/` are using `arr.modDims` and change those as well ? (except `modDims` function ofcourse :) )

**Comment by 9prady9** [comment]
Sure

**Comment by 9prady9** [comment]
There is only file `histeq.cpp` that used that and i changed that now.

**Pull request merged**
